### ISSUE TITLE
Retornar robôs para site

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#106]
Conforme sugerido [neste comentário](https://github.com/automatiza-mg/automatizacoes/issues/76#issuecomment-1996073831) do issue #76.

**Comment by Andrelamor** [comment]
## decisões de leiaute da página para reincorporar MVPs do SEI ao novo modelo
1. numerar os subfluxos em cada caixinha
2. nota de rodapé explicando que subfluxos são opcionais
3. abrir subfluxos em nova aba do navegador em vez de sobrepor à página aberta
4. levar para o _subtitle_ "Montando seu robô"_

**Comment by Andrelamor** [comment]
@gabrielbdornas [troca unidade sei](https://github.com/automatiza-mg/automatizacoes/pull/107/commits/f780745507fcfde3f5aaf6621f357631aea16781)
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/5c7b720b-092e-4c2c-961f-5bd5045abbcb)

**Comment by Andrelamor** [comment]
@gabrielbdornas decidi retornar com o MVP que cria processo novo, pois [o de buscar já existente é tão pequeno](https://github.com/automatiza-mg/biblioteca-de-robos/blob/main/robos/site/processo_existente_sei.txt) e vai dar tanto trabalho nessas microdecisões de leiaute... veja aí a sugestão
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/8cd9890d-135b-4310-a571-86f578d1f603)

**Comment by Andrelamor** [comment]
@gabrielbdornas ao vincluar o PRa este issue, quando vc mergeou, ele fechou, certo? mas ainda temos o mvp terminal, o que a Isa mandou e um fluxo repetido, listando abaixo:
- [ ] mvp terminal prodemge
- [ ] mvp descompactação e verificação de arquivos 
- [ ] fluxo criação processo em vez de troca unidade sei

**Comment by Andrelamor** [comment]
> * [ ]  mvp descompactação e verificação de arquivos

adicionados 3 protótipos da Isa na biblioteca, a conferir e posteriormente incluir no site:
https://github.com/automatiza-mg/biblioteca-de-robos/commit/7ea1f658a8a82606710a557aa4824da1e750d6f7

**Comment by YanVieira1905** [comment]
Recebemos muitos pedidos para que incluamos todos os robôs no site, independentemente, de serem compartilháveis ou não. @gabrielbdornas, você consegue um relatório do % de pessoas que acessam essa página divididos em MG e fora do estado? Acho que vai ser um bom subsídio para pensarmos em como organizar.

**Comment by gabrielbdornas** [comment]
> Recebemos muitos pedidos para que incluamos todos os robôs no site, independentemente, de serem compartilháveis ou não. @gabrielbdornas, você consegue um relatório do % de pessoas que acessam essa página divididos em MG e fora do estado? Acho que vai ser um bom subsídio para pensarmos em como organizar.

Acredito que tem essa info no Analytics sim (acessos por região). Acho que vale abertura de um Issue para realizarmos a extração automática desta informação. para separarmos os assuntos.

Sobre incluir todos os robôs no site acho que não faz sentido. Penso que podemos criar um post sobre como acessar a [biblioteca de robôs](https://github.com/automatiza-mg/biblioteca-de-robos/).
