### ISSUE TITLE
Adicionar sistema de avaliação de páginas

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#110]
Seguindo o proposto no #109 e na [documentação](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=analy#was-this-page-helpful).

Retirar das páginas que esta avaliação não faz sentido, tais como landing page e biblioteca de robôs. Deixar nas páginas dos robôs e blog.

@dcd-github-admin, na opinião de vocês é interessante deixar esta avaliação na página do formulário de apoio e em sua confirmação? Vou deixar até segunda ordem.

## Tarefas

- [x] Incluir link para avaliação nas páginas adequadas.
- [x] Criar formulário Tally.
- [x] [Ligar avaliações no Analytics](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=ana#was-this-page-helpful).
- [x] Conferir se configuração Analytics está funcionando. Segundo a documentação Material, "The report may take 24 hours or longer to begin displaying data"

**Comment by Andrelamor** [comment]
> Seguindo o proposto no #109 e na [documentação](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=analy#was-this-page-helpful).
> 
> Retirar das páginas que esta avaliação não faz sentido, tais como landing page e biblioteca de robôs. Deixar nas páginas dos robôs e blog.
> 
> @dcd-github-admin, na opinião de vocês é interessante deixar esta avaliação na página do formulário de apoio e em sua confirmação? Vou deixar até segunda ordem.

@gabrielbdornas a qual avaliação vc fez referência, tem como contextualizar melhor pra nós por favor? tem o link da issue do Analytics e o da documentação no MKDocs

**Comment by gabrielbdornas** [comment]
Ainda não consegui conectar a avaliação da página aos relatórios Analytics.

**Comment by Andrelamor** [comment]
certo, acabei de preencher 2 formas de teste

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas a qual avaliação vc fez referência, tem como contextualizar melhor pra nós por favor? tem o link da issue do Analytics e o da documentação no MKDocs

@Andrelamor, claro:

Ao final da página como [esta](https://automatiza-mg.github.io/automatizacoes/robos/busca_numeros_documentos_processo_sei/#montando-o-seu-robo) agora temos:

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/3fb334d9-4955-4476-8c5f-98fbd526be76)

É possível também mandar sugestões:

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/db4505a0-29f2-40d2-bf7c-6c28f36e77f2)

**Comment by Andrelamor** [comment]
@gabrielbdornas não ficou registrada a URL da página que avaliei, no tally: https://tally.so/forms/w480k5/submissions
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/7ad046b7-07fc-4d9c-abba-b508198906c2)

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas não ficou registrada a URL da página que avaliei, no tally: https://tally.so/forms/w480k5/submissions ![image](https://private-user-images.githubusercontent.com/52294411/320144416-7ad046b7-07fc-4d9c-abba-b508198906c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODAzMTAsIm5iZiI6MTcxMjU4MDAxMCwicGF0aCI6Ii81MjI5NDQxMS8zMjAxNDQ0MTYtN2FkMDQ2YjctMDdmYy00ZDljLWFiYmEtYjUwODE5ODkwNmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyNDAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2OTJhNDQ2MjMzZmU2OTYwZDY2NGNmZWIyY2Y1MDM3MDBhOGQxYzIxZDBhN2UyY2VkZGY3ZDEzMzgyZTQ1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZ8iP575S4Es_fpfiPjLnLXC30v1Ile2xrtdw9iT8yE) vai ficar na dependência do usuário preencher manualmente mesmo, né..olha, 50 caracteres é muito pouco: ![image](https://private-user-images.githubusercontent.com/52294411/320145472-762eaa53-431d-4613-bc5b-d93361ac37e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODAzMTAsIm5iZiI6MTcxMjU4MDAxMCwicGF0aCI6Ii81MjI5NDQxMS8zMjAxNDU0NzItNzYyZWFhNTMtNDMxZC00NjEzLWJjNWItZDkzMzYxYWMzN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyNDAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyM2E3MmU3NGUxODc3NTAxNTRhYjczOTYyMjVjZWM0MGFmMTc0YTNhMTFhM2U2N2ZmYjNkMjFmNzhjODhlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Exz-FX_sm0gXjV4jqHMNLsQ-o-DFc0tamtflO52QXVc)

@Andrelamor, deve ter sido algum problema de atualização do Tally, pois agora está aparecendo, veja:

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/804721df-ac07-4718-8a44-d293ba1ea3ff)

Aproveitei para fazer 2 manutenções no formulário:

- Colocar o campo de link como não obrigatório.
- Colocar o campo de sugestão com no mínimo 30 caracteres (estava no máximo 50).

**Comment by Andrelamor** [comment]
> @Andrelamor, deve ter sido algum problema de atualização do Tally, pois agora está aparecendo, veja:

reescrevendo com outras palavras: se o usuário não copiar e colar, o link da URL não aparece automaticamente : 
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/69cfc6f7-04c0-48e8-bdf4-33826eeabc34)

**Comment by gabrielbdornas** [comment]
> e, se não for obrigatório, não saberemos a qual página o usuário fez menção na avaliação

Pensei nisso, mas fiquei com medo do usuário não "saber" copiar o link da página (principalmente se ele estiver navegando no celular. Como o campo de nome e e-mail são obrigatórios, pensei em entrar em contato caso seja necessário (sugestão sem link e sem dicas no texto principal). Você acha resolveria? Ou melhor deixar o campo de link obrigatório mesmo?

**Comment by Andrelamor** [comment]
> > e, se não for obrigatório, não saberemos a qual página o usuário fez menção na avaliação
> 
> Pensei nisso, mas fiquei com medo do usuário não "saber" copiar o link da página (principalmente se ele estiver navegando no celular). Como o campo de nome e e-mail são obrigatórios, pensei em entrar em contato caso seja necessário (sugestão sem link e sem dicas no texto principal). Você acha resolveria? Ou o melhor será realmente deixar o campo de link obrigatório?

Entendi, vamos ver o que vai vir... o caso de uso 'celular', argumento que não deveria ser considerado. Pouco provável que seja um usuário que esteja com interesse, de fato, em navegar, copiar o código, construir um robô no Power Automate. A não ser que a pessoa consiga uma versão 'mobile' do Power Automate e copie e cole o código do protótipo, pelo celular...

**Comment by gabrielbdornas** [comment]
@dcd-github-admin, [configuração](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=analy#:~:text=How%20to%20visualize%20the%20collected%20feedback%20ratings%3F) realizada em 25/05/2024:

>Go to your Google Analytics dashboard
> 
> Go to the configure page on the left hand menu, then select custom definitions
> 
> Click the custom metrics tab and then create custom metrics, enter the following values:
> 
> Metric name: Page helpful
> Description: Was this page helpful?
> Event parameter: data
> Unit of measurement: Standard

![Image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/82f22c78-70ea-4f31-998b-d76888ca7869)

> Go to the explore page on the left hand menu, create a new blank exploration
>
> Configure the report as follows:
>
> Dimensions: Add Event name and Page location
> Metrics: Add Event count and Page helpful (the custom metric created in step 3)
> Rows: Page location
> Values: Drag in both Event count and Page helpful
> Filters: Add a new filter for Event name / exactly matches / feedback

![Image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/233a014b-7d06-4dd6-b43c-5d8b6c5f8a03)

![Image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/e9e866ba-c3d6-423f-8d02-63f4ad9be2af)

**Comment by gabrielbdornas** [comment]
@dcd-github-admin, avaliação funcionando, conforme conferência realizada dia 26/04/2024:

![Image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/5d0237b4-07d7-4616-a312-f8dccdd3e4c5)
