### ISSUE TITLE
editar regras para divulgação ampla (disclaimer) de Robôs (protótipos)

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#12]
Atualmente não conseguimos compartilhar robôs do power automate devido ao plano contratado. Teria algum problema compartilhar o código copiado em um repositório GitHub.

Solicitei Patrick para entrar em contato com Henrique da Intendência para realizar esta análise.

**Comment by gabrielbdornas** [comment]
> Porém, ressalto que, sem ter conhecimento das cláusulas do contrato, não é possível te dar esse embasamento legal.

@patrickciampi, perfeito, ficamos aguardando então esta análise nas cláusulas do contrato.

Incluo aqui @Andrelamor para acompanhamento. Acredito que issue está relacionado com o #6.

**Comment by Andrelamor** [comment]
pessoal, fiz algumas sugestões para o documento que o @patrickciampi está produzindo([versão de hoje]()); eu me inspirei em experiência recente de minutar um [termo de uso para o Portal de Dados Abertos](https://github.com/transparencia-mg/transparencia-mg-estatico/blob/aspectos-legais-responsabilidades/content/aspectos-legais-responsabilidades/aspectos-legais-responsabilidades.md), que foi baseado no do portal Federal e que adotou um estilo _'responsabilidades das partes: mantenedor do portal e usuário'_  e autoaplicável (tipo contrato de adesão/anuência tácita)

**Comment by Andrelamor** [comment]
> Sobre o compartilhamento, ele afirmou que todos os produtos produzidos durante o período de vigência do contrato são de propriedade de quem os criou. Na visão dele, você é o responsável pelo seu conteúdo, como os fluxos elaborados, o que permitiria o seu compartilhamento.

Prezados, se me permitem uma analogia, não pedimos permissão à Microsoft para enviar planilhas de excel por email, ou fazer delas datawarehouses de paineis que são publicados na web. De tal forma que qualquer produto de um programa com licença paga teria o mesmo tratamento, tal qual @patrickciampi nos informou acima.

**Comment by Andrelamor** [comment]
exemplos de termos de uso, com responsabilidades e questões de privacidade:
- [ponto digital MG](https://www.pontodigital.mg.gov.br/anexos/termos.pdf);
- [serpro](https://www.serpro.gov.br/privacidade-protecao-dados/termos-gerais-de-uso-tgu_v3-2.pdf)

**Comment by gabrielbdornas** [comment]
@Andrelamor, este Issue ainda faz sentido?

**Comment by Andrelamor** [comment]
> @Andrelamor, este Issue ainda faz sentido?

temos que ver com @lucasfainblat e @YanVieira1905

**Comment by gabrielbdornas** [comment]
@Andrelamor e @YanVieira1905, ainda faz sentido este Issue? Iremos incluir alguns disclaimer no site?

**Comment by Andrelamor** [comment]
> @Andrelamor e @YanVieira1905, ainda faz sentido este Issue? Iremos incluir alguns disclaimer no site? Se sim, o texto criado inicialmente pelo Patrick poderá ser aproveitado? Qual sugestão de vocês de lugar para ele "morar" dentro do site?

@gabrielbdornas @YanVieira1905 propus um termo geral no formato de adesão, diferente do anterior, que tinha um tom mais contratual e fiscalizatório; creio que poderia estar localizado no rodapé, 

Se ainda faz sentido? Bem, um argumento que registrei [aqui](https://github.com/automatiza-mg/automatizacoes/issues/84#issuecomment-1988943078)para sustentar sua aplicação está em responsabilizar qualquer usuário, especialmente quando participar em comentários (seja sistema do github ou outro)

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas @YanVieira1905 propus um termo geral no formato de adesão, diferente do anterior, que tinha um tom mais contratual e fiscalizatório; creio que poderia estar localizado no rodapé, exemplo no [Portal de Transparência](https://www.transparencia.mg.gov.br/).
> 
> Se ainda faz sentido? Bem, um argumento que registrei [aqui](https://github.com/automatiza-mg/automatizacoes/issues/84#issuecomment-1988943078) para sustentar sua aplicação está em responsabilizar qualquer usuário, especialmente quando participar em comentários (seja sistema do github ou outro)

@Andrelamor, perfeito. Vamos seguir com a inclusão. Gosto dos argumentos. [Neste comentário incluído acima](https://github.com/automatiza-mg/automatizacoes/issues/12#issuecomment-1781775123) parece conter um link para a última versão do texto, mas não consegui acessar o documento.

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/4a1576dc-b91a-4e68-9f62-cd743183a2c8)

Você tem a permissão para liberar? Se sim, já incluo ele em um arquivo `markdonw` no repositório e trabalhamos com sua atualização versionada.

**Comment by gabrielbdornas** [comment]
Documento atualizado.

[Termo de Anuência - com adaptações.pdf](https://github.com/automatiza-mg/automatizacoes/files/14616731/Termo.de.Anuencia.-.com.adaptacoes.pdf)

**Comment by YanVieira1905** [comment]
> > [@Andrelamor](https://github.com/Andrelamor) e [@YanVieira1905](https://github.com/YanVieira1905), ainda faz sentido este Issue? Iremos incluir alguns disclaimer no site? Se sim, o texto criado inicialmente pelo Patrick poderá ser aproveitado? Qual sugestão de vocês de lugar para ele "morar" dentro do site?
> 
> [@gabrielbdornas](https://github.com/gabrielbdornas) [@YanVieira1905](https://github.com/YanVieira1905) propus um termo geral no formato de adesão, diferente do anterior, que tinha um tom mais contratual e fiscalizatório; creio que poderia estar localizado no rodapé, exemplo no [Portal de Transparência](https://www.transparencia.mg.gov.br/).
> 
> Se ainda faz sentido? Bem, um argumento que registrei [aqui](https://github.com/automatiza-mg/automatizacoes/issues/84#issuecomment-1988943078) para sustentar sua aplicação está em responsabilizar qualquer usuário, especialmente quando participar em comentários (seja sistema do github ou outro)

Faz sentido sim. Gosto bastante deste do portal da transparência. Fica escondido no final da página, mas tem tudo o que precisamos lá. @gabrielbdornas, acha tranquilo incluir isto no rodapé e uma página assim no site?

**Comment by gabrielbdornas** [comment]
> Faz sentido sim. Gosto bastante deste do portal da transparência. Fica escondido no final da página, mas tem tudo o que precisamos lá. @gabrielbdornas, acha tranquilo incluir isto no rodapé e uma página assim no site?

Tranquilo sim @YanVieira1905. Farei!

**Comment by YanVieira1905** [comment]
@gabrielbdornas, o que falta para encerrarmos esse issue?

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas, o que falta para encerrarmos esse issue?

Incluir o texto feito por Patrick lá no site. Seria bom revisar ele também, já que foi criado no início do projeto. De lá para cá muita coisa já mudou. Se puder ler a [última versão](https://github.com/automatiza-mg/automatizacoes/issues/12#issuecomment-1999773311) seria ótimo!

**Comment by YanVieira1905** [comment]
Achei que ficou parecendo um contrato. Acho que não faz muito sentido. Acha que seria possível fazer no site uma forma que, ao clicar no link para acessar o código do robô, o usuário seja direcionado para um texto de disclaimer neste sentido: 

"Termo de Uso

Este termo aplica-se ao uso da biblioteca de robôs disponibilizada pelo projeto Automatiza.MG, operado pela Secretaria de Estado de Planejamento e Gestão de Minas Gerais ("Seplag-MG"). Ao acessar e utilizar a biblioteca de robôs, você ("Usuário") reconhece e concorda com os termos aqui estabelecidos.

1. Geral

A biblioteca de robôs do Automatiza.MG oferece uma variedade de robôs de automatização destinados a facilitar e otimizar processos administrativos no âmbito do serviço público. Estes robôs são fornecidos "como estão", sem garantias de qualquer tipo, seja expressa ou implícita.

2. Isenção de Garantias

A Seplag-MG, seus diretores, funcionários e parceiros não oferecem garantias sobre a completude, confiabilidade, disponibilidade, atualidade, segurança, ausência de erros ou precisão dos robôs ou do conteúdo disponibilizado na biblioteca de robôs. O uso dos robôs é por sua conta e risco.

3. Limitação de Responsabilidade

Sob nenhuma circunstância, a Seplag-MG, seus diretores, funcionários ou parceiros serão responsáveis por quaisquer danos diretos, indiretos, incidentais, especiais, consequenciais ou punitivos, incluindo, sem limitação, perda de lucros, dados, uso, boa-fé ou outras perdas intangíveis, resultantes do seu acesso ou uso, ou da incapacidade de acessar ou usar os robôs da biblioteca.

4. Uso Adequado

O Usuário concorda em utilizar os robôs de automatização exclusivamente para fins legítimos e de acordo com as leis e regulamentações aplicáveis. O uso indevido dos robôs é estritamente proibido e sujeito a ações legais.

5. Modificações e Disponibilidade

A Seplag-MG reserva-se o direito de modificar, suspender ou descontinuar, temporária ou permanentemente, a biblioteca de robôs ou qualquer serviço a ela relacionado, com ou sem aviso prévio. A Seplag-MG não será responsável perante o Usuário ou terceiros por qualquer modificação, suspensão ou descontinuação do serviço.


Ao utilizar a biblioteca de robôs do Automatiza.MG, o Usuário reconhece que leu, entendeu e concordou em estar vinculado por esta Isenção de Responsabilidade."?

E daí coletaria os dados dele via google analytics, se possível. 

O que acha?

**Comment by gabrielbdornas** [comment]
> Achei que ficou parecendo um contrato. Acho que não faz muito sentido. Acha que seria possível fazer no site uma forma que, ao clicar no link para acessar o código do robô, o usuário seja direcionado para um texto de disclaimer neste sentido:

@YanVieira1905, gostei da ideia. Vou pesquisar se é possível fazer este redirecionamento no mkdocs-material. Acredito que é possível.

Contraponto: Será que não ficará muito "chato" ter que clicar toda hora neste disclaimer. Poderíamos, por exemplo, só incluir uma frase em algum lugar na página do robô apontando para o texto.

**Comment by gabrielbdornas** [comment]
@raianecardoso, queria sua ajuda para fecharmos este Issue. A ideia é revisarmos o texto criado inicialmente e propor um local no site para guardá-lo.

**Comment by raianecardoso** [comment]
> @raianecardoso, queria sua ajuda para fecharmos este Issue. A ideia é revisarmos o texto criado inicialmente e propor um local no site para guardá-lo.

Claro, @gabrielbdornas!

Eu fiquei na dúvida quanto ao formato do documento (termo, contrato, política, etc). Isso dá o tom da redação, então acho que esse é o primeiro ponto de definição. Depois reviso (revisamos) a redação.

Nesse sentido,  é necessário que este seja um termo que o usuário confirme a sua anuência? Entendi que vocês se inspiraram em outros modelos para propor que fosse dessa forma, mas não há obrigatoriedade legal, certo?

Se este for o caso, eu sugiro que tenhamos uma página com a nossa "política de segurança e responsabilidades", na mesma linha do [Portal da Transparência](https://www.transparencia.mg.gov.br/aspectos-legais-e-responsabilidades) mencionado acima.

**Comment by raianecardoso** [comment]
@gabrielbdornas @Andrelamor @YanVieira1905 

Pessoal, fiz uma proposta de redação considerando o que foi discutido nesse issue: [Termos de uso: Aspectos legais e segurança ](https://cecad365.sharepoint.com/:w:/r/sites/LAB.mg/Documentos%20Compartilhados/General/7.%20DCD/Automatiza.MG/Proposta%20de%20pol%C3%ADtica%20de%20privacidade%20e%20seguran%C3%A7a.docx?d=w81d7d51e485d425daaf7b37e02180306&csf=1&web=1&e=O7exhY)

Após a revisão da redação, sugiro que essa seja uma página do nosso site e o que link para ela esteja ao final da nossa página da biblioteca de robôs.

**Comment by YanVieira1905** [comment]
Achei ótimo Raiane. Fiquei só com uma dúvida sobre o item: "As marcas presentes na página da Biblioteca de robôs, incluindo a logomarca de Governo, são de propriedade do Governo do Estado de Minas Gerais, sendo proibida sua reprodução, cópia ou modificação sem expressa autorização do Governo do Estado de Minas Gerais". 

Isso não seria público?

**Comment by raianecardoso** [comment]
> Achei ótimo @raianecardoso. Fiquei só com uma dúvida sobre o item: "As marcas presentes na página da Biblioteca de robôs, incluindo a logomarca de Governo, são de propriedade do Governo do Estado de Minas Gerais, sendo proibida sua reprodução, cópia ou modificação sem expressa autorização do Governo do Estado de Minas Gerais".
> 
> Isso não seria público?
> 
> @gabrielbdornas, sobre o local, acho que a gente pode colocar como um link no meio da descrição da primeira frase da página de biblioteca de robôs. Algo neste sentido: "Aqui estão catalogados robôs produzidos durante treinamentos e projetos específicos desenvolvidos pelo Automatiza-mg. Esses são de livre utilização, devendo ser observados os termos de uso (link no "termos de uso")".
> 
> O que acham?

@YanVieira1905

não, uso de marca precisa ser autorizado. Quando vc firma alguns instrumentos jurídicos, como convênios e termos de parceria, é comum este texto vir como cláusula padrão. De todo modo, eu retirei esse trecho do portal da transparência. Se eles estiverem errados, a gente tem uma boa desculpa haha! 😅 

Quanto ao locak do link na página, achei sua sugestão ótima!

**Comment by gabrielbdornas** [comment]
@raianecardoso e @YanVieira1905, gostei de todas as sugestões. PR #146 aberto para avaliação de vocês.
