### ISSUE TITLE
Reunião CET - Desbloqueio de GRAVAME

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#121]
Submission `4Pkvqb` dos pedidos de apoio.

Relato do processo:

> "A Diretoria de Gestão dos Credenciamentos de Veículos- DGCV, recebe da Empresa B3, planilhas com solicitações de desbloqueio de gravames, que na prática é o cancelamento de reserva de financiamento de veículos, a ser tratado manualmente no Sistema do Departamento de Trânsito de Minas Gerais (SDAK), pelos Servidores da DGCV.
>
> A empresa B3 é a responsável junto a Coordenadoria Estadual de Trânsito- CET pela inserção, alteração e baixa de gravames financeiros em veículos emplacados em Minas Gerais. Os dados dos veículos, que por algum motivo, não foram processados na empresa B3, são encaminhados para a DGCV para que inserção no SDAK e correção do chamado “erro 98”.
>
> As planilhas são enviadas, diariamente pela Empresa B3, para o e-mail credenciamento.veiculos@transito.mg.gov.br, com informações dezenas de veículos, para desbloqueio de gravames e demais tratativas referentes a pendências de gravames financeiros de veículos. Essas planilhas recebidas na DGCV, são distribuídas entre os servidores e tratadas manualmente no SDAK.
> 
> Constam nas planilhas as seguintes informações a respeito dos veículos:
> 
> • chassi do veículo
> • placa do veículo,
> • data de pagamento da DAE pela transação,
> • CPF/CNPJ do financiado,
> • número de identificação da DAE,
> • motivo do desbloqueio,
> • código de protocolo,
> • Unidade da Federação da placa do veículo.
> 
> Tratativas dos Servidores no SDAK - Chamada de rotina de “correção erro 98”
> 
> O operador do SDAK, copia os dados do veículo da planilha enviada pela B3 e cola no sistema SDAK, na tela destinada ao DESBLOQUEIO DO CANCELAMENTO DA RESERVA DE FINANCIAMENTO.
> 
> O cancelamento será feito no SDAK, seguindo os seguintes comandos:
> 
> PF-1 Menu Principal - Veículos
> 32 - Menu Gravames
> 11 – Cancelamento de reserva de financiamentos
> 
> Serão preenchidos com “N” os campos abaixo descritos:
> 
> • cancelamento por determinação judicial,
> • cancelamento por Leilão,
> • cancelamento administrativo.
> • veículo isento da taxa de serviço
> 
> Em seguida, serão inseridas as datas, conforme informadas na planilha e pressionada a tecla “enter”.
> Por fim deverá ser colocado o motivo do desbloqueio, e pressionado F5 para efetuar o desbloqueio.
> 
> Observação: Após o procedimento a informação poderá ser verificada na opção (PF1-32/11) – Desbloqueio do cancelamento da reserva de financiamento
"

## Perguntas

- Podemos ver a planilha enviada por e-mail? É Enviada através de um email único?
- É realizado algum ajuste/correção na planilha recebida?
- SDAK é terminal PRODEMGE? Sim Podemos ter login e senha para já iniciar a construção do robô? Será avaliado
- Alguns motivos para o erro 98 e por que a própria empresa não pode resolver? Inserção manual, tratativa diferente do processo inicialmente informado devido a falta de informação na DAE
- Quantos servidores ficam responsáveis por isso hoje? 03 servidores
- O número informado de 60 lançamentos por dia, 3 minutos por processo, é uma estimativa pensada, ou foi lançada aleatoriamente somente para conseguir preencher o formulário? Informação validada pela área
- A comprovação do cancelamento tem que ser incluída em algum outro sistema? É respondido o email com a informação de que o registro foi realizado com sucesso e a informação de pendências se necessário
- Algum servidor da Diretoria para absorver o conhecimento e dar manutenção no futuro robô? Victor irá acompanhar e responsável por futuras manutenções
- Algum computador, novo, disponível para implantarmos o robô? A área possuí computador

**Comment by gabrielbdornas** [comment]
- Natália irá verificar liberação das senhas com acessos somente para as telas necessárias.
- Envia e-mail informando que os registros são feitos.
- Natália irá mandar uma planilha de determinação judicial para tratarmos.

**Comment by felpsop** [comment]
- A Náthalia irá solicitar a B3 inserção de todos os campos
- Será realizada a construção de um robô inicial para casos de fluxo completo, sem anomalias
- O servidor Victor irá acompanhar a construção do robô
