### ISSUE TITLE
Otimização do robô de listar processos no SEI

### ISSUE THREAD

**Issue by bruno-rsantos** [automatiza-mg/automatizacoes#122]
[lista_processos_unidade.txt](https://github.com/automatiza-mg/automatizacoes/files/15099548/lista_processos_unidade.txt)

Esse algoritmo realiza uma forma mais ágil de leitura e gravação dos processos SEI recebidos em uma unidade do sistema.

Considerando que grande parte dos processos a serem automatizados precisam listar e entrar em todos processos SEI de uma unidade, o algoritmo em questão consegue ser mais ágil, reduzindo significativamente o tempo de execução desta tarefa dentro do fluxo completo.

Ao final, a variável de fluxo "lista_final" conterá todos números de processos da unidade SEI selecionada, bem como será criado um arquivo Excel, cuja primeira coluna ("A") conterá a lista dos processos.

**Comment by Andrelamor** [comment]
@bruno-rsantos conforme testamos hoje, avaliar se o protótipo vai funcionar com somente 2 páginas de processo na unidade SEI escolhida. Talvez funcione somente para 3 páginas ou mais (mais de 100 processos), que tem o dropdown de páginas, ao contrário das unidades com menos de 100 processos (2 páginas) que tem o objeto abaixo printado, parece não estar evidente na ferramenta inspecionar: 
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/4a02379d-215f-458b-951c-39ff5d3c3209)

**Comment by gabrielbdornas** [comment]
> @bruno-rsantos conforme testamos hoje, avaliar se o protótipo vai funcionar com somente 2 páginas de processo na unidade SEI escolhida. Talvez funcione somente para 3 páginas ou mais (mais de 100 processos), que tem o dropdown de páginas, ao contrário das unidades com menos de 100 processos (2 páginas) que tem o objeto abaixo printado, parece não estar evidente na ferramenta inspecionar:

@bruno-rsantos, lembrar também das diferenças ocasionadas pela instalação de plugins SEI. Temos que pensar como o robô trataria estas situações. Exemplo. Plugin [Sei++](https://chromewebstore.google.com/detail/sei++/jkngjemcdoglnkbbdekpnkgfbpoldcck) adiciona elementos na tabela de processos gerados.

**Comment by bruno-rsantos** [comment]
@gabrielbdornas @Andrelamor realizei as correções no robô e atualizei a versão na biblioteca de robôs.
Agora funciona tanto com SEi++ ativado ou sem o plugin. E também funciona para qualquer quantidade de páginas e processos da unidade.

https://github.com/automatiza-mg/biblioteca-de-robos/blob/main/robos/lista_processos_unidade_SEI.txt

**Comment by Andrelamor** [comment]
@dcd-github-admin diante do último comentário do @bruno-rsantos, e considerando que eu já usei esse robô está funcionando, estou fechando este issue
