### ISSUE TITLE
Adicionar thumb no vídeo "Webinar Automatiza-MG #4"

### ISSUE THREAD

**Issue by henriquesiqr** [automatiza-mg/automatizacoes#137]
O vídeo foi editado (recorte) e adicionado ao youtube do Automatiza. Basta adicionar a thumb do vídeo.

**Comment by gabrielbdornas** [comment]
Done!

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/fe90f320-d3b7-4c25-ba37-0640b12b3378)
