### ISSUE TITLE
adaptar fluxo de envio de certificados e compartilhamento de infos das turmas

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#14]
Atualmente, a gestão do envio de certificados está na conta privada individual do sharepoint do Lucas.
Cada documento ou pasta adicional devem ter permissão de acesso.
As planilhas e nomes das respectivas pastas que dão base ao certificado são editadas com as datas, números de turma e participantes de fato.
A emissão dos certificados usa pacotes do R mas depende de integração libreoffice para transformar o pptx em pdf.
O email é enviado manualmente com um texto-padrão e permissão de acesso a uma pasta no sharepoint onde os pdf ficam salvos. 

Conforme me repassou o Lucas, poderiam ser repensadas as formas de execução desse processo, via sharepoint para todos envolvidos ou até mesmo github actions.

**Comment by Andrelamor** [comment]
O formato dos números da tabela que consolida os robôs compartilhados não está legível/manipulável, apenas como texto

**Comment by gabrielbdornas** [comment]
@Andrelamor, o que acha de criarmos um conjunto de dados para essa lista? Você vê algum problema em relação a dados pessoais? Estando em formato aberto podemos incluir o envio via actions. um problema neste sentido é marcar a presença dos alunos. Hoje ela é feita em uma planilha do Excel e a usabilidade é relativamente fácil. Marcar isso em um arquivo csv não seria tão fácil assim.

**Comment by gabrielbdornas** [comment]
@YanVieira1905, @Andrelamor e eu resolvemos fechar este Issue, tendo em vista as modificações na estrutura do curso que serão realizadas.
