### ISSUE TITLE
Revisão páginas de robôs SEI - Evento SEI

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#156]
- [x] Documento externo.
- [x] Cria memorando.
- [x] Assina e encaminha.
- [x] Criar página robô Prompt Memo (@Andrelamor).
- [x] Incluir Excel página criar documento externo (@gabrielbdornas).
- [x] Incluir códigos na biblioteca de robôs (@augustacora).
  - [x] Revisar criar processo (novos tabs no lugar de clicar).
  - [x] Documento externo.
  - [x] Memorando.
  - [x] Prompt.
  - [x] Assinar e enviar.
- [ ] Gravar vídeo (@augustacora). 
- [x] reconferir páginas criadas e editadas
  - [x] testar links
  - [x] nomes subfluxos
  - [x] nomes variáveis
  - [x] copiar e colar os códigos

**Comment by Andrelamor** [comment]
Verificar variável `caminho_excel` inexistente no código de cria_memorando
>   * [x]  Memorando.

>   * [ ]  nomes variáveis

**Comment by Andrelamor** [comment]
Faltaram várias explicações das informações do documento externo a ser anexado, na planilha-modelo incluí pelo https://github.com/automatiza-mg/automatizacoes/commit/337490aa143ded4e6811c7e1eb70c895bc396001
