### ISSUE TITLE
Criar post(s) com dicas de Excel

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#16]
Mencionado [nesta reunião](https://lab-mg.github.io/handbook/atas/20231018_estrutura_paginas_projeto_automatizacoes/#acoes), a criação de posts com dicas de Excel poderá ajudar no processo de construção de robôs, além de incentivar o aperfeiçoamento profissional de servidores.

**Comment by Andrelamor** [comment]
fonte para estudo e elaboração do post: https://learn.microsoft.com/en-US/training/modules/pad-excel-automation/

**Comment by Andrelamor** [comment]
@gabrielbdornas botei no ar um primeiro post sobre esse assunto porque:
1. vejo que é a maioria das fontes das dificuldades dos fluxos no projeto da SCAP; 
2. já têm meia dúzia de casos de uso e fórmulas interessantes pra ajudar; 
 
de qualquer forma, podemos aplicar controles de versão e atualizar/melhorar os posts, ou desmembrá-lo posteriormente:
https://lab-mg.github.io/automatizacoes/blog/modificar-dados-no-excel/

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas botei no ar um primeiro post sobre esse assunto porque:
> 
> 1. vejo que é a maioria das fontes das dificuldades dos fluxos no projeto da SCAP;
> 2. já têm meia dúzia de casos de uso e fórmulas interessantes pra ajudar;
> 
> de qualquer forma, podemos aplicar controles de versão e atualizar/melhorar os posts, ou desmembrá-lo posteriormente: https://lab-mg.github.io/automatizacoes/blog/modificar-dados-no-excel/

@Andrelamor, achei que o post ficou sensacional. Neste primeiro momento acho que não precisamos desmembrá-lo. A medida que os casos de uso incluídos aumentem, podemos pensar no caso de desmembrar. Estou pensando em fazer algumas sugestões de melhorias no curso de Automate e acho que pedir as pessoas para lerem este Post antes do curso pode ajudar muito.

**Comment by Andrelamor** [comment]
@gabrielbdornas acho que vale mais 2 posts com os casos práticos das manipulações do excel que vimos/fizemos nos treinamentos e no projeto de imersão da SCAP; assim, para os próximos treinamentos. enviamos os links dos posts para preparação
