### ISSUE TITLE
ocultação de autoria e marcas de autoria no site para inova

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#162]
Temos uma questão prática de ocultar nomes, fotos e links que levem para marcas de nossa autoria, enquanto estivermos no período de avaliações das propostas do INOVA. Na parte do site, é relativamente tranquilo (página inicial e blog), mas resta o link para o repositório. O site só funciona, a princípio, com o repositório aberto (se fechar, o site cai). Se alguém da comissão avaliadora clicar no link que leva para o repositório, todos os nossos nomes e fotos estarão lá. 
Minhas sugestões de alterações provisórias[^1]:
- [x] retirar [depoimentos](https://automatiza-mg.github.io/automatizacoes/#depoimentos) 
- [x] retirar [equipe](https://automatiza-mg.github.io/automatizacoes/#conheca-nossa-equipe), mantendo uma caixa para email de contato, com imagem da nossa logo oficial em vez da foto de alguém
- [x]  retirar fotos e nomes dos autores dos posts do Blog
  - [ ] atualizar avatar do usuário master com a logo [aqui](https://github.com/dcd-github-admin) 
- [ ] REPOSITÓRIO: retirar, temporariamente, todos autores, exceto @dcd-github-admin ; isso implica em 'congelar' o repositório para qualquer edição de usuários, exceto o [usuário master](https://github.com/orgs/automatiza-mg/people/dcd-github-admin)
  - [ ] retirar usuários @gabrielbdornas @Andrelamor [aqui](https://github.com/automatiza-mg/automatizacoes/settings/access)
  - [ ] mesmo assim, confirmar se alterações passadas permanecem om nomes e fotos das pessoas 
[^1]: até a conclusão do INOVA

**Comment by YanVieira1905** [comment]
Minha sugestão seria de utilizar prints do site como anexo, e anonimizar os nomes.

**Comment by Andrelamor** [comment]
> Uma dúvida, a que nível é essa ocultação de autoria? Teremos que apagar os posts do Automatiza no Instagram, por exemplo? A equipe toda aparece lá

Eu abri essa questão se caso alguém cite o link do site. A sugestão do Yan, se entendi, elimina a citação direta do link do site e substitui por prints.  Se vc citar o Instagram, principalmente em algum trecho sobre estratégia de multiplicação, seria o mesmo caso.

**Comment by raianecardoso** [comment]
Pessoal, vou colocar como referencia o que diz o Manual do Proponente: 

> NÃO SE IDENTIFIQUE ao longo do formulário de inscrição ou nos anexos. Alguns exemplos de formas de identificação QUE NÃO DEVEM SER FEITAS são: escrever ao longo do trabalho os nomes dos proponentes ou anexar documentos, planilhas, trabalhos acadêmicos, apresentações e imagens que contenham dados pessoais, de identificação funcional, endereço de e-mail ou mesmo fotos de qualquer integrante do grupo;

**Comment by Andrelamor** [comment]
> Pessoal, vou colocar como referencia o que diz o Manual do Proponente:
> 
> > NÃO SE IDENTIFIQUE ao longo do formulário de inscrição ou nos anexos. Alguns exemplos de formas de identificação QUE NÃO DEVEM SER FEITAS são: escrever ao longo do trabalho os nomes dos proponentes ou anexar documentos, planilhas, trabalhos acadêmicos, apresentações e imagens que contenham dados pessoais, de identificação funcional, endereço de e-mail ou mesmo fotos de qualquer integrante do grupo;

Então, os hiperlinks não podem ser citados nas propostas, caso contrário demanda essa [trabalheira que listei](https://github.com/automatiza-mg/automatizacoes/issues/162#issue-2570711692), da qual a ocultação de marcas de autoria no repositório em si e no Instagram me parecem inviáveis. Então acho que a sugestão do Yan contemplou, com os devidos cuidados

**Comment by gabrielbdornas** [comment]
@automatiza-mg/dcd , uma alternativa poderia ser realmente fechar o repositório. Como andre citou usando o github pages o site cai. Poderíamos utilizar, então outro serviço, como read the docs.

**Comment by raianecardoso** [comment]
Pessoal, considerando que não foram necessárias essas adequações, estou fechando este issue!
