### ISSUE TITLE
tags dos blogs não aceitam caracteres especiais

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#33]
@gabrielbdornas depois de reler o [erro](https://github.com/lab-mg/automatizacoes/issues/31#issuecomment-1779875810) da tentativa de executar `mkdocs serve`, percebi que as `tags` criadas nos posts do blog não aceitam acentos, caso contrário o site estático não é gerado localmente.

Para eu conseguir ver minhas alterações, retirei os acentos dos posts criados, pelo menos provisoriamente, [neste commit](https://github.com/lab-mg/automatizacoes/commit/f613b90cf7327456d2a49a98af0e38cfc78495c0).

Posteriormente uma solução definitiva pode ser aplicada. Por ora, estou focando na uniformização dos modelos para as páginas dos robôs.

**Comment by gabrielbdornas** [comment]
@Andrelamor, vou tentar reproduzir este erro aqui. Incluí o issue na próxima sprint.

**Comment by gabrielbdornas** [comment]
@Andrelamor, tentei reproduzir o erro na minha máquina, mas o servidor rodou normalmente:

![image](https://github.com/lab-mg/automatizacoes/assets/49699290/1a34e190-520f-4c39-9440-5b3846f3df39)

![image](https://github.com/lab-mg/automatizacoes/assets/49699290/d89d053d-93cf-46c1-8444-982eb9cc7cd6)

Perceba que ele retira automaticamente os acentos e caracteres especiais durante a criação da URL.

Tive [problemas parecidos](https://github.com/lab-mg/automatizacoes/issues/31#issuecomment-1779875810) trabalhando na máquina Windows da CAMG e o problema era o encoding Python entendido pelo Windowns, que atrapalhava seu funcionamento no Git Bash. [Para corrigir](https://stackoverflow.com/a/53516312/11755155) bastou cadastrar a variável de ambiente `PYTHONIOENCODING` com valor `utf-8`.

**Comment by Andrelamor** [comment]
> @Andrelamor, tentei reproduzir o erro na minha máquina, mas o servidor rodou normalmente:
> 
> ![image](https://user-images.githubusercontent.com/49699290/282481651-1a34e190-520f-4c39-9440-5b3846f3df39.png)
> 
> ![image](https://user-images.githubusercontent.com/49699290/282481878-d89d053d-93cf-46c1-8444-982eb9cc7cd6.png)
> 
> Perceba que ele retira automaticamente os acentos e caracteres especiais durante a criação da URL.
> 
> Tive [problemas parecidos](https://github.com/lab-mg/automatizacoes/issues/31#issuecomment-1779875810) trabalhando na máquina Windows da CAMG e o problema era o encoding Python entendido pelo Windowns, que atrapalhava seu funcionamento no Git Bash. [Para corrigir](https://stackoverflow.com/a/53516312/11755155) bastou cadastrar a variável de ambiente `PYTHONIOENCODING` com valor `utf-8`.

teste de colocar `utf-8` em minúsculo não resolveu problema de parsear acentos gráficos no meu notebook windows; a verificar melhor

**Comment by gabrielbdornas** [comment]
> teste de colocar `utf-8` em minúsculo não resolveu problema de parsear acentos gráficos no meu notebook windows; a verificar melhor

@Andrelamor, para termos certeza de que a configuração foi realmente efetivada, seria possível rodar o comando `echo $PYTHONIOENCODING` em um novo terminal e incluir aqui o resultado.

[Outra alternativa](https://dev.to/methane/python-use-utf-8-mode-on-windows-212i) seria cadastrar a variável `PYTHONUTF8` igual a `1`. Sugiro também rodar `echo $PYTHONUTF8` para confirmar sua configuração.

**Comment by gabrielbdornas** [comment]
> > teste de colocar `utf-8` em minúsculo não resolveu problema de parsear acentos gráficos no meu notebook windows; a verificar melhor
> 
> @Andrelamor, para termos certeza de que a configuração foi realmente efetivada, seria possível rodar o comando `echo $PYTHONIOENCODING` em um novo terminal e incluir aqui o resultado.
> 
> [Outra alternativa](https://dev.to/methane/python-use-utf-8-mode-on-windows-212i) seria cadastrar a variável `PYTHONUTF8` igual a `1`. Sugiro também rodar `echo $PYTHONUTF8` para confirmar sua configuração.

@Andrelamor, vou me tirar do Issue, deixando-o aberto para a próxima sprint, pois entendo que esta é uma incompatibilidade entre máquinas que temos que corrigir.

Se o proposto acima não funcionar, me inclua aqui novamente. Se preferir, podemos marcar uma hora de debug na próxima semana.

**Comment by gabrielbdornas** [comment]
@Andrelamor, vamos agendar uma hora esta semana para tentar fechar este Issue?

**Comment by Andrelamor** [comment]
> [@Andrelamor](https://github.com/Andrelamor), vamos agendar uma hora esta semana para tentar fechar este Issue?

@gabrielbdornas não sei por quê essa notificação passou batido, mas sim, veja que horas vc poderia por favor? Outras questões (#76 #81 [carga SISAD](https://github.com/automatiza-mg/imersao-scap/issues/13) e [robô FISCAP](https://github.com/automatiza-mg/imersao-scap/issues/15)) tomaram o tempo nesta semana...

**Comment by Andrelamor** [comment]
em novo teste de agora os caracteres especiais funcionaram 
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/3d59f5ba-9b6a-43e5-9a6a-eafe81e62953)
