### ISSUE TITLE
criar post com lista de dificuldades recorrentes no uso das ações do PA durante a montagem dos fluxos e alternativas

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#35]
@gabrielbdornas pensei em catalogar uma lista de exemplos de substituição de ações que são pensadas mas não funcionam para determinados fluxos, e um pouco de contexto (alternativas, prós, contras) sobre cada uma dessas situações que encontrei; se achar que isso tem valor, poderíamos expandir ou quebrar o post em um para cada tipo de situação

por enquanto deixei em draft, [aqui](https://github.com/lab-mg/automatizacoes/blob/main/docs/blog/posts/20231108_lista_dificuldades/index.md)

**Comment by Andrelamor** [comment]
## impossível copiar código por faltar definição ou relação de variável ou instância

![image](https://github.com/lab-mg/automatizacoes/assets/52294411/edd9942f-8c18-4b23-b251-7c4c85400fe0)

**Comment by Andrelamor** [comment]
@gabrielbdornas penso que o post deste issue poderia ser material complementar (follow-up) dos treinamentos/curso moodle do PA, seguindo tuas sugestões em #39

**Comment by Andrelamor** [comment]
- como maximizar excel ao abrir? como sobrepor janela do excel em cima da janela do power automate?

**Comment by IsaRomancini** [comment]
Acho que poderia ter imagens dos erros recorrentes. Tem alguns que consigo fazer aqui para tirar print. 
Ex:
- Variáveis que não existem
- Elementos não encontrados na página
- Erro que dá quando não tem a extensão instalada

@Andrelamor quando eu coloco espaço em alguma frase na ação "cortar texto", o automate aceita. Quando eu quero cortar uma frase que está entre espaços ou entre "enter", eu crio uma variável que chama "espaço" e peço para o automate cortar texto a partir dessa variável. Assim ele aceita. 
Inclusive, quando precisa substituir um texto por nada, eu uso a mesma estratégia. Se criar uma variável com nada dentro, o automate consegue utilizá-la no fluxo.

**Comment by Andrelamor** [comment]
> Acho que poderia ter imagens dos erros recorrentes. Tem alguns que consigo fazer aqui para tirar print. 
> Ex:
> - Variáveis que não existem
> - Elementos não encontrados na página
> - Erro que dá quando não tem a extensão instalada
Ótima ideia, @IsaRomancini ! Se puder colar por aqui os prontos que vc já tem, agradeço!
> @Andrelamor quando eu coloco espaço em alguma frase na ação "cortar texto", o automate aceita. Quando eu quero cortar uma frase que está entre espaços ou entre "enter", eu crio uma variável que chama "espaço" e peço para o automate cortar texto a partir dessa variável. Assim ele aceita. 
> Inclusive, quando precisa substituir um texto por nada, eu uso a mesma estratégia. Se criar uma variável com nada dentro, o automate consegue utilizá-la no fluxo. 

Essa estratégia de criação de variáveis merece um post próprio no blog, hein?

**Comment by gabrielbdornas** [comment]
> Essa estratégia de criação de variáveis merece um post próprio no blog, hein?

Ontem, em conversas com a equipe do Lab tivemos a ideia de criar pequenos vídeos (reels) para divulgação no Instagram. Poderíamos criar duas séries de vídeos, uma para mostrar erros recorrentes e outra para mostrar dicas. Assim, no lugar de prints poderíamos incluir o link para os vídeos.

**Comment by IsaRomancini** [comment]
Essa semana eu simulo os erros e coloco o print aqui. 
Eu gosto da ideia do reels, mas tem que conversar com Ana sobre isso, porque como Automatiza é um projeto separado, não sei se poderia colocar direto no instagram do LAB ou como ficariam as postagens.

**Comment by Andrelamor** [comment]
> Essa semana eu simulo os erros e coloco o print aqui. Eu gosto da ideia do reels, mas tem que conversar com Ana sobre isso, porque como Automatiza é um projeto separado, não sei se poderia colocar direto no instagram do LAB ou como ficariam as postagens.

aí a gente vê @gabrielbdornas como fica essa questão do formato das imagens pesando a página; talvez a gente coloca 2 ou 3 pra testes?

**Comment by Andrelamor** [comment]
publiquei sem imagens por enquanto em https://automatiza-mg.github.io/automatizacoes/blog/causas-comuns-de-erros-na-montagem-dos-fluxos-dos-rob%C3%B4s/

**Comment by IsaRomancini** [comment]
Erro: variável não existe
![Erro variável não existe](https://github.com/automatiza-mg/automatizacoes/assets/76135149/02b3da8c-a6c2-4a61-8316-d1a5d8c2bc4c)
**O que fazer:** criar uma variável com o nome exato que aparece no erro. Pode ser uma variável de entrada ou uma variável criada dentro do fluxo

Erro: falha ao assumir o controle do Google Chrome
![image](https://github.com/automatiza-mg/automatizacoes/assets/76135149/793df67a-0acc-4157-8a9d-79823bda19e4)
**O que fazer**: ativar extensão no navegador

**Comment by gabrielbdornas** [comment]
@Andrelamor, este Issue está classificado como "Done". Podemos fechá-lo?

**Comment by Andrelamor** [comment]
Acho que é mais um dos que registramos ideias, começa-se um trabalho e não tem uma tração esperada de todos na mesma direção. Vou fechar, mas fechar não implica que a versão publicada é a definitiva, assim como várias outras partes do site e do projeto como um todo. Fica o alerta de que teremos várias partes de ideias iniciadas ou feitas parcialmente nos issues fechados. Mas pelo menos isso é melhor que não ter registrado por escrito em algum lugar
