### ISSUE TITLE
listar possíveis ações de robô para 3 subprocessos do CET

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#36]
## etapas necessárias
- ler e compreender valores de campos de documentos físicos digitaliaados e ou manuscritos (a verificar possibilidade de uso da IA em reunião com Lucas Araújo dia 16/11);
- baixar e renomear arquivos do SEI;
- incluir arquivos no sistema próprio do CET (protocolo digital)

**Comment by Andrelamor** [comment]
## baixar e renomear arquivos do SEI
- `obter arquivos na pasta` e ou `copiar arquivos`;
- `Renomear arquivos`, verificar opções de `renomear esquema`

**Comment by Andrelamor** [comment]
* acompanhar desdobramentos da iniciativa/parceria com Google/Embratel/PRODEMGE de arquitetura de solução de IA para o CET: https://lab-mg.github.io/handbook/atas/20231117_seplag_prodemge_google_embratel_IA_CET/

**Comment by Andrelamor** [comment]
https://cecad365-my.sharepoint.com/personal/m7527781_ca_mg_gov_br/_layouts/15/onedrive.aspx#id=%2fpersonal%2fm7527781_ca_mg_gov_br%2fDocuments%2fArquivos+de+Chat+do+Microsoft+Teams&FolderCTID=0x012000D2427089A7C255469FDD66ECC6A3AA20&view=0

**Comment by YanVieira1905** [comment]
Reunião agendada para o dia 26/03 com a CET. Iremos apresentar o projeto e, posteriormente, eles irão listar, pelo formulário, processos que acham que podemos trabalhar. Irei aproveitar para apresentar o robô de infrações.

**Comment by YanVieira1905** [comment]
Projeto em andamento. A priorização foi da defesa de autos de infração.
