### ISSUE TITLE
Sugestões de melhorias curso Power Automate

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#39]
@Andrelamor, quero registrar aqui algumas ideias de melhorias no Curso de Power Automate, especialmente pensando na nova fase de 2024:

- **Sala**: Este assunto é polêmico, mas acredito que devemos tocar nele em algum momento. A sala atual utilizada é muito grande e as pessoas que ficam no fundo, não conseguem enxergar a projeção do monitor. Penso que teríamos que pensar na troca para uma experiência mais confortável para os alunos. Alternativas são a sala de informática da FJP ou a sala do 9° Andar do prédio Gerais. As desvantagens seriam, respectivamente, o deslocamento para um lugar diferente da CAMG e uma sala com capacidade menor de alunos.
- **Conteúdos complementares**: acredito que passar alguns conteúdos preliminares ajudaria em um melhor entendimento dos alunos. Uma espécie de "dever de casa" não obrigatório, mas recomendado. Um bom exemplo seria o post [Modificar dados no excel](https://lab-mg.github.io/automatizacoes/blog/modificar-dados-no-excel/). Acho, inclusive, que esta lista pode ser definida em alguma página de nosso documento online.
- **Introdução um pouco maior**: hoje fazemos uma introdução muito rápida sobre o que é a ferramenta Power Automate e já vamos para a mão na massa. Acho que para fins didáticos, deveríamos fazer uma introdução maior, mostrando um pouco mais a ferramenta em si. Pensei em fazer um breve tour sobre a tela, explicando, por exemplo, o que são ações e como incluí-las no fluxo. Explicar com pequenos exemplos o que são condições e loops também deixaria os alunos menos confusos durante a prática concreta.
- **Criar um certificado de conclusão do curso com número maior de horas**: uma das iniciativas para incentivar a criação de robôs poderia ser a criação de um certificado de conclusão de curso com mais horas para pessoas que nos enviarem vídeos de robôs criados após a capacitação.

Obs.: Estes são os que me ocorreram até o momento. Pretendo ir rechiando ao longo do tempo. Fique a vontade para complementar.

**Comment by Andrelamor** [comment]
@gabrielbdornas concordo com todas, eu já havia comentado com o pessoal sobre as dificuldades dos alunos das últimas fileiras na sala atual, é bem difícil enxergar;
- sobre o excel, acho que vale encaminhar os links dos posts que fizermos sobre isso, no momento em que a turma for agendada;
- sobre a introdução, sugiro coisa similar ao item anterior -  envio do link com material estático de coisas preparatórias, como https://lab-mg.github.io/automatizacoes/blog/criar-e-editar-instancias-e-variaveis-no-power-automate/ (o que não exclui a necessidade de replicar essa introdução ampliada ao vivo, durante o curso - mas diminuímos a chance de dificuldades com isso pelos alunos)

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas concordo com todas, eu já havia comentado com o pessoal sobre as dificuldades dos alunos das últimas fileiras na sala atual, é bem difícil enxergar;
> 
> * sobre o excel, acho que vale encaminhar os links dos posts que fizermos sobre isso, no momento em que a turma for agendada;
> * sobre a introdução, sugiro coisa similar ao item anterior -  envio do link com material estático de coisas preparatórias, como https://lab-mg.github.io/automatizacoes/blog/criar-e-editar-instancias-e-variaveis-no-power-automate/ (o que não exclui a necessidade de replicar essa introdução ampliada ao vivo, durante o curso - mas diminuímos a chance de dificuldades com isso pelos alunos)

@Andrelamor, para facilitar a vida do Lucas podemos criar um pequeno post com estes links e uma breve explicação. Ou você pensou em algum outro formato?

**Comment by Andrelamor** [comment]
- aproveitamento dos cursos é percebido como baixo; fazer para entrada em imersões ou manter expectativa de formar fazedores de robôs?

**Comment by Andrelamor** [comment]
diretriz recebida em 10/01, de focar os cursos na plataforma EAD/Moodle da SEPLAG, em parceria com TCE

**Comment by gabrielbdornas** [comment]
Analisar o que poderá ser aproveitado após decisão das mudanças de formato do curso, em especial para a modalidade EaD.

**Comment by gabrielbdornas** [comment]
@lucasfainblat, @YanVieira1905, @Andrelamor, fecharei este issue em favor do #69.
