### ISSUE TITLE
embedar arquivo pdf no site estático

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#44]
Isso vai ser bem útil para visualizar arquivos de relatórios feitos em powerpoint que podem ser salvos em formatos pdf no próprio repositório
Um passo-a-passo para fazer referência ou embedar o arquivo pdf do repositório: https://stackoverflow.com/questions/69237778/how-to-embed-a-local-pdf-file-in-mkdocs-generated-website-on-github-pages
Caso a configuração fique muito trabalhosa, podemos tentar fazer referência a um arquivo com acesso irrestrito a partir de uma pasta no google drive, conforme descrito na pergunta que originou o passo-passo acima

**Comment by Andrelamor** [comment]
paths não encontrados após alterações do passo-a-passo:
````
INFO    -  [16:23:27] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [16:23:27] Serving on http://127.0.0.1:8000/
WARNING -  [16:23:28] "GET /projetos/scap/%7B%7B%20pdf_file%20%7D%7D HTTP/1.1"
           code 404
WARNING -  [16:23:28] "GET /projetos/scap/docs/assets/reports/Proposta_SCAP.pdf
           HTTP/1.1" code 404
INFO    -  [16:23:29] Browser connected: http://127.0.0.1:8000/projetos/scap/
WARNING -  [16:23:29] "GET /projetos/scap/%7B%7B%20pdf_file%20%7D%7D HTTP/1.1"
           code 404
WARNING -  [16:23:29] "GET /projetos/scap/docs/assets/reports/Proposta_SCAP.pdf
           HTTP/1.1" code 404
````

**Comment by gabrielbdornas** [comment]
@Andrelamor, acredito que podemos fechar este Issue, pois encontrei uma maneira de incluir arquivos no site. Ao clicar no link proposto para o arquivo, o sistema faz o download dele automaticamente. Exemplo de utilização aqui:

https://github.com/automatiza-mg/automatizacoes/blob/017345cfed9b2c9f5bcd0e462cebee1af7612112/docs/robos/consulta_situacao_cadastral_cagef/index.md?plain=1#L39-L41

Caso ache necessário abra-o novamente.
