### ISSUE TITLE
Melhorias páginas robôs e projeto PAE

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#47]
Em 06/12/2023 fiz reunião com Giovanna e Fernanda para algumas definições das páginas robôs e projeto PAE. As sugestões foram incluídas em um [note](https://cecad365.sharepoint.com/sites/LAB.mg/_layouts/15/Doc.aspx?sourcedoc={1b6f6628-51ba-4705-8b78-1f18b5ddd2f9}&action=edit&wd=target%2805.%20Tarefas%20do%20Plano%20de%20A%C3%A7%C3%A3o.one%7C3d827c81-2fdf-45fb-8b45-18ce949a0edd%2F8%20-%20GitHub%7C05c4bf1d-6c14-4552-b02b-94b67c69519e%2F%29&wdorigin=NavigationUrl).
Combinamos de ver as melhorias dia 07/12/2023 na parte da tarde.

**Comment by Andrelamor** [comment]
- robôs do PAE publicados e revisados
- definição posterior à conversa no lab.mg foi retirada da página de projetos
- questões de modelo das páginas discutidas, decididas e registradas nos outros issues relativos à página do Automatiza
