### ISSUE TITLE
Cursos Automate 2024 - planejamento

### ISSUE THREAD

**Issue by lucasfainblat** [automatiza-mg/automatizacoes#49]
## Planejamento 2024 dos cursos de Automate:

- [Últimas atualizações aqui](https://github.com/lab-mg/automatizacoes/issues/49#issuecomment-1869540292)
- [Página do produtor LAB.MG no Sympla](https://organizador.sympla.com.br/meus-eventos)

### Preliminares
- **Mini seminário** entre professores: padronizar conteúdo e didática do curso
    - Incorporar _loops à la PVC_ - não necessita ajustar o processo todo, etapa por etapa, inserindo a variável
    - Montar introdução com exposição de elementos e conceitos básicos anteriores à "mão na massa"

### Formato
- Cursos somente de **funcionalidades básicas**
    - Planejamento semestral
    - Cursos especiais combinados por fora (processo Y ou turma do órgão X)
    - Gravação de um curso EaD de ciclo básico, disponível para qualquer um a qualquer tempo
       - Certificação após cumprir critérios

- Local, dias/horários e capacidade alternados (alunos com agendas fixas têm mais opção de aderir às vagas):
    - **Laboratório de Informática da FJP**, com capacidade de **20 vagas** por curso - sempre às **quartas-feiras**
    - **Sala de Treinamento da SEPLAG**, com **13 vagas** por curso - sempre às **quintas-feiras**.

- Divulgação e inscrições
   - Canal ou grupão de Zap (aproveitar para divulgar novidades do repositório e ocasiões em que houver vagas disponíveis na véspera dos treinamentos)
   - Inscrições via Sympla ou similar (necessário: emitir certificados automáticos; alimentar base de dados de inscritos e certificados; possibilitar inscrições restritas - só inscreve com código, para turmas especiais)

### Follow-up
- Follow-up do tipo **mini imersão**, por adesão no curso
    - Por formulário
    - 3 reuniões semanais de 1 hora para ajudar a elaborar um robô ou ajustar um processo
    - Certificado complementar

### Equipe
- Cada curso utiliza 1 professor e 3 monitores, que obedecerão a rodízio

- Professores:
    - @gabrielbdornas 
    - @Andrelamor 
    - Yan
    - Isa

- Monitores:
    - @gabrielbdornas 
    - @Andrelamor 
    - Yan
    - Isa
    - Lucas
    - Maria Laura

#### Proposta 1 - frequência semanal

| Data       | Local                      | Vagas | Professor | Monitores                        |
|------------|----------------------------|-------|-----------|----------------------------------|
| 25/01/2024 | Laboratório de Informática | 20    | Gabriel   | Gabriel, André, Lucas            |
| 01/02/2024 | Sala de Treinamento        | 13    | Yan       | Lucas, Maria Laura, Yan          |
| 08/02/2024 | Laboratório de Informática | 20    | Isa       | Maria Laura, Yan, Isa            |
| 15/02/2024 | Sala de Treinamento        | 13    | André     | Yan, Isa, Lucas                  |
| 22/02/2024 | Laboratório de Informática | 20    | Gabriel   | Isa, Lucas, André                |
| 29/02/2024 | Sala de Treinamento        | 13    | Yan       | Lucas, André, Maria Laura        |
| 07/03/2024 | Laboratório de Informática | 20    | Isa       | André, Maria Laura, Yan          |
| 14/03/2024 | Sala de Treinamento        | 13    | André     | Maria Laura, Yan, Isa            |
| 21/03/2024 | Laboratório de Informática | 20    | Gabriel   | Yan, Isa, Lucas                  |
| 28/03/2024 | Sala de Treinamento        | 13    | Yan       | Isa, Lucas, André                |
| 04/04/2024 | Laboratório de Informática | 20    | Isa       | Lucas, André, Maria Laura        |
| 11/04/2024 | Sala de Treinamento        | 13    | André     | André, Maria Laura, Yan          |
| 18/04/2024 | Laboratório de Informática | 20    | Gabriel   | Maria Laura, Yan, Isa            |
| 25/04/2024 | Sala de Treinamento        | 13    | Yan       | Yan, Isa, Lucas                  |
| 02/05/2024 | Laboratório de Informática | 20    | Isa       | Isa, Lucas, André                |
| 09/05/2024 | Sala de Treinamento        | 13    | André     | Lucas, André, Maria Laura        |
| 16/05/2024 | Laboratório de Informática | 20    | Gabriel   | André, Maria Laura, Yan          |
| 23/05/2024 | Sala de Treinamento        | 13    | Yan       | Maria Laura, Yan, Isa            |
| 30/05/2024 | Laboratório de Informática | 20    | Isa       | Yan, Isa, Lucas                  |
| 06/06/2024 | Sala de Treinamento        | 13    | André     | Isa, Lucas, André                |
| 13/06/2024 | Laboratório de Informática | 20    | Gabriel   | Lucas, André, Maria Laura        |
| 20/06/2024 | Sala de Treinamento        | 13    | Yan       | André, Maria Laura, Yan          |
| 27/06/2024 | Laboratório de Informática | 20    | Isa       | Maria Laura, Yan, Isa            |

Total de Vagas Ofertadas
Laboratório de Informática: 240 vagas
Sala de Treinamento**: 156 vagas
**Total: 396 vagas**

Total de Carga Horária Ofertada
Cada curso semanal tem carga horária de 6 horas.
24 semanas de curso.
**Total de Carga Horária Ofertada: 144 horas**

#### Proposta 2 - frequência quinzenal

| Data       | Local                      | Vagas | Professor | Monitores                        |
|------------|----------------------------|-------|-----------|----------------------------------|
| 25/01/2024 | Laboratório de Informática | 20    | Gabriel   | Gabriel, André, Lucas            |
| 08/02/2024 | Sala de Treinamento        | 13    | Yan       | André, Lucas, Maria Laura        |
| 22/02/2024 | Laboratório de Informática | 20    | Isa       | Lucas, Maria Laura, Yan          |
| 07/03/2024 | Sala de Treinamento        | 13    | André     | Maria Laura, Yan, Isa            |
| 21/03/2024 | Laboratório de Informática | 20    | Gabriel   | Yan, Isa, Lucas                  |
| 04/04/2024 | Sala de Treinamento        | 13    | Yan       | Isa, Lucas, André                |
| 18/04/2024 | Laboratório de Informática | 20    | Isa       | Lucas, André, Maria Laura        |
| 02/05/2024 | Sala de Treinamento        | 13    | André     | André, Maria Laura, Yan          |
| 16/05/2024 | Laboratório de Informática | 20    | Gabriel   | Maria Laura, Yan, André          |
| 30/05/2024 | Sala de Treinamento        | 13    | Yan       | Yan, André, Isa                  |
| 13/06/2024 | Laboratório de Informática | 20    | Isa       | André, Isa, Maria Laura          |
| 27/06/2024 | Sala de Treinamento        | 13    | André     | Isa, Maria Laura, Gabriel        |

Total de Vagas Ofertadas
Laboratório de Informática: 120 vagas
Sala de Treinamento: 78 vagas
**Total: 198 vagas**

Total de Carga Horária Ofertada
Cada curso quinzenal tem carga horária de 6 horas.
12 semanas de curso.
**Total de Carga Horária Ofertada: 72 horas**

**Comment by lucasfainblat** [comment]
### Atualizações - 26/12

#### Planejamento de cursos 🗓
Após reunião com Camila, em seu gabinete, em 20/12, com presença de @lucasfainblat e @gabrielbdornas, ficou combinado o calendário de capacitações mensais, mas começando com 3 cursos entre o fim de janeiro e o fim de fevereiro. Os cursos serão disponibilizados no Sympla e publicados somente na véspera, gerando uma "_corrida pelas vagas_". A próxima seção traz o novo cronograma anual.

### Cronograma[^1]:
| Turma                | Data       | Hora          | Local                                  | N. de Vagas | Professor          | Monitores                                          | Link do Sympla                |
|----------------------|------------|---------------|----------------------------------------|-------------|---------------------|----------------------------------------------------|-------------------------------|
| <ul><li>- [ ] 2024.1</li></ul> | 31/01/2024 | 9h30 - 12h30  | Laboratório de Informática da FJP      | 20          | Gabriel Dornas      | André Amorim, Yan Vieira                           | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.2</li></ul> | 08/02/2024 | 9h30 - 12h30  | Sala de Treinamento da SEPLAG           | 13          | André Amorim        | Yan Vieira, Isa Romancini                          | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.3</li></ul> | 28/02/2024 | 9h30 - 12h30  | Laboratório de Informática da FJP      | 20          | Yan Vieira          | Isa Romancini, Lucas Fainblat                      | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.4</li></ul> | 07/03/2024 | 9h30 - 12h30  | Sala de Treinamento da SEPLAG           | 13          | Isa Romancini       | Lucas Fainblat, Maria Laura                        | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.5</li></ul> | 04/04/2024 | 9h30 - 12h30  | Laboratório de Informática da FJP      | 20          | Gabriel Dornas      | André Amorim, Yan Vieira                           | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.6</li></ul> | 02/05/2024 | 9h30 - 12h30  | Sala de Treinamento da SEPLAG           | 13          | André Amorim        | Yan Vieira, Isa Romancini                          | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.7</li></ul> | 06/06/2024 | 9h30 - 12h30  | Laboratório de Informática da FJP      | 20          | Yan Vieira          | Isa Romancini, Lucas Fainblat                      | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.8</li></ul> | 04/07/2024 | 9h30 - 12h30  | Sala de Treinamento da SEPLAG           | 13          | Isa Romancini       | Lucas Fainblat, Maria Laura                        | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.9</li></ul> | 01/08/2024 | 9h30 - 12h30  | Laboratório de Informática da FJP      | 20          | Gabriel Dornas      | André Amorim, Yan Vieira                           | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.10</li></ul>| 05/09/2024 | 9h30 - 12h30  | Sala de Treinamento da SEPLAG           | 13          | André Amorim        | Yan Vieira, Isa Romancini                          | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.11</li></ul>| 03/10/2024 | 9h30 - 12h30  | Laboratório de Informática da FJP      | 20          | Yan Vieira          | Isa Romancini, Lucas Fainblat                      | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.12</li></ul>| 07/11/2024 | 9h30 - 12h30  | Sala de Treinamento da SEPLAG           | 13          | Isa Romancini       | Lucas Fainblat, Maria Laura                        | <ul><li>- [ ] Link</li></ul> |
| <ul><li>- [ ] 2024.13</li></ul>| 05/12/2024 | 9h30 - 12h30  | Laboratório de Informática da FJP      | 20          | Gabriel Dornas      | André Amorim, Yan Vieira                           | <ul><li>- [ ] Link</li></ul> |


[^1]: "turma" fica "ticada" quando o respectivo curso for concluído; "link" fica "ticado" quando o post do sympla estiver publicizado.

#### Seminário de professores 🎓
Ficou marcado para 11/01, na Sala de Treinamento da Seplag, entre 9h30 e 12h30.
Convites enviados para:
"Yan Vieira do Carmo (SEPLAG)" <yan.carmo@planejamento.mg.gov.br>; "Isabela Romancini Ribeiro (SEPLAG)" <isabela.romancini@planejamento.mg.gov.br>; "Gabriel Braico Dornas" <gabriel.dornas@planejamento.mg.gov.br>; "Andre Luiz Guimaraes Amorim (SEPLAG)" <andre.amorim@planejamento.mg.gov.br>; "Pedro Vinicius (pedro.campos@fazenda.mg.gov.br)" <pedro.campos@fazenda.mg.gov.br>; "Luigi Caetano da Silva (SEDESE)" <luigi.silva@social.mg.gov.br>; "Isabela Romancini Ribeiro (SEPLAG)" <isabela.romancini@planejamento.mg.gov.br>; "Maria Laura Gontijo Tolentino (SEPLAG)" <maria.gontijo@planejamento.mg.gov.br>

#### Pendengas:
- Confirmar cronograma com Yan --> utilizar agenda Lucas/Yan de 28/12, às 15h30.
- Reservar espaços dos cursos --> enviar e-mails ao Ivan Machado e à Larissa, da FJP.

**Comment by Andrelamor** [comment]
https://github.com/lab-mg/automatizacoes/issues/39#issuecomment-1889088244

**Comment by gabrielbdornas** [comment]
@lucasfainblat, @YanVieira1905, @Andrelamor, fecharei este Issue em favor do #69.
