### ISSUE TITLE
Mudar nome organização GitHub para automatiza-mg.

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#65]
Conforme decidido em [reunião dia 12/01/2024](#64).

- [x] Mudar nome organização.
- [x] Atualizar logo.
- [x] Atualizar remotes.
- [x] Enviar mensagem para todos da equipe solicitando atulização dos remotes.

**Comment by gabrielbdornas** [comment]
@Andrelamor, @augustacora e @YanVieira1905 após renomear uma organização temos que atualizar os remotes em nossas máquinas. Remote é o link que faz a conexão entre o repositório no GitHub com os arquivos locais em nossas máquinas. Acredito que, neste momento, quem terá este "problema" será apenas o @Andrelamor. Comandos a serem executados (alto nível):

```python
cd <repo-name> # Entra no repositório desejado
git remote rm origin # Remove o remote origin
git remote -v # Visualiza os remotes cadastrados para confirmar deleção
git remote add origin <caminho-remote> # Cadastra novamente com o nome da organização atualizado
git remote -v # Visualiza os remotes cadastrados para confirmar o cadastro
```
- O `<caminho-remote>` pode ser obtido na página GitHub do repositório.

- Exemplo de atualização para o repositório "automatizacoes":

```python
➜  automatizacoes git:(main) git remote rm origin # Remove o remote origin
➜  automatizacoes git:(main) git remote -v # Visualiza os remotes cadastrados para confirmar deleção
➜  automatizacoes git:(main) git remote add origin git@github.com:automatiza-mg/automatizacoes.git # Cadastra novamente com o nome da organização atualizado
➜  automatizacoes git:(main) git remote -v # Visualiza os remotes cadastrados para confirmar o cadastro
origin	git@github.com:automatiza-mg/automatizacoes.git (fetch)
origin	git@github.com:automatiza-mg/automatizacoes.git (push)
```

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/c6292bf6-21f7-4a3b-b4ff-4ead7166d1e1)

**Comment by gabrielbdornas** [comment]
@Andrelamor o commit [Atualiza novo nome organizacao github](https://github.com/automatiza-mg/automatizacoes/commit/2f19fba4aff64e72aed65c6c5ded6db71cca83ae) se mostrou um exemplo de manutenção causada por links Markdown criados não utilizando caminhos para arquivos. Abaixo um exemplo mais específico:

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/9557472f-8159-445f-8ae3-e42d7f32ff86)

**Comment by Andrelamor** [comment]
@gabrielbdornas como a alteração foi paliativa, ainda restam alterações dos caminhos relativos, em vez dos links dos docs publicados no site; vou reabrir este issue, embora não seja tema do assunto principal, e citar as correções de caminhos relativos aqui

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas como a alteração foi paliativa, ainda restam alterações dos caminhos relativos, em vez dos links dos docs publicados no site; vou reabrir este issue, embora não seja tema do assunto principal, e citar as correções de caminhos relativos aqui

Perfeito! Precisar de ajuda é só falar.
