### ISSUE TITLE
robôs MVPs: listagem, organização, publicação e revisão

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#71]
@gabrielbdornas @IsaRomancini @YanVieira1905 

- MVPs do SEI nesta semana (22~~26) e testes na próxima
 
## SEI

- denominar instância SEI no Automate (variável de fluxo) de `sei`
- utilizar subfluxos (um para login, outro para troca de unidade)

- utilizar variáveis e comentários
    - padrão nomenclatura variáveis : `minusculas_sem_caracteres_especiais_ou_espacos`
- primeiro modelo dos robôs, depois modelo das páginas
- roteiro para vídeo dos robôs
**Lista robôs** 
- [x] fazer login: https://automatiza-mg.github.io/automatizacoes/robos/login_sei/ @gabrielbdornas 
- [x] trocar unidade do SEI: https://automatiza-mg.github.io/automatizacoes/robos/sei_troca_unidade/
    - mudar código para colocar Órgão como Variável de entrada @Andrelamor (partir do ícone da lista de processos por causa do tab)
- [x] selecionar processo (novo ou colar número do processo existente) ou documento (para assinatura, p. ex.) e criar processo público ou restrito @YanVieira1905 
- [ ] criar documento (**ação** `exibir seleção na caixa de diálogo de lista` qual documento? restrito, sim ou não? cliques em caixa de diálogo em vez de copiar e colar de texto em aspas de comentários; colocar número de memorando na variável de entrada): @Andrelamor 
    - público ou restrito
        - doc exerno ou ofício ou memorando: https://automatiza-mg.github.io/automatizacoes/robos/sei_cria_processo_documento/
        
- [ ] Extrair dados dos processos que estão em um bloco interno e passar essa lista para um excel: https://automatiza-mg.github.io/automatizacoes/robos/sei_bloco_interno_processos/ vide https://github.com/automatiza-mg/automatizacoes/issues/66

- [x] assinatura @YanVieira1905 
- [ ] enviar processo @YanVieira1905 

-  IA
- [ ] Enviar prompt para chatGpt e armazenar respostas em planilha Excel. @gabrielbdornas 

## EXCEL online e EMAIL
- [ ] acessar aba de planilha online e enviar email, após conferência de datas-gatilho dos eventos

## Loop em Texto
- [x] caso da anonimização de CPF: robô dos atos da aposentadoria [já postado no Automatiza](https://automatiza-mg.github.io/automatizacoes/robos/aposentadoria/), incluindo [post com explicação](https://automatiza-mg.github.io/automatizacoes/blog/como-modificar-uma-express%C3%A3o-regular-em-um-texto/)

## SISAP
- [ ] progressão e promoção (a saber se carga massiva pela PRODEMGE tem custo proibitivo - agenda com Diniz)

## PDF
- [ ] Extrair tabelas de um pdf e passar para excel. 
- [ ] extrair texto de guia em pdf: https://automatiza-mg.github.io/automatizacoes/robos/texto_pdf/

**Comment by IsaRomancini** [comment]
**Fluxo Criar processo e documento no SEI**
- Alterar código do robô para 
[Criar processo e documento no SEI.txt](https://github.com/automatiza-mg/automatizacoes/files/13980565/Criar.processo.e.documento.no.SEI.txt)

Eu retirei a variável de entrada "Órgão" dele

- Acho que pode retirar o fluxo do robô, pois ele é muito simples.
- Na seção "Importante", acrescentar: "Verifique se o nome do seu órgão já consta no campo "órgão" na tela de login do SEI. Caso não conste, entre no SEI com suas credenciais e, logo após fazer o login, saia do sistema. Assim, seu órgão ficará como padrão na tela de login
- Na seção "Além disso", acho que pode retirar "Revisar o(s) caminho(s) de arquivo(s) (PATH).", pois nesse código não tem nenhum arquivo

**Comment by IsaRomancini** [comment]
**Fluxo "trocar unidade do SEI"**
- Não sei se precisa, mas acho legal ter aquela seção de "Funções desenvolvidas pelo robô" com as atividades. O fluxo desenhado acho que não precisa. 
- Na seção "Importante", acrescentar: "Verifique se o nome do seu órgão já consta no campo "órgão" na tela de login do SEI. Caso não conste, entre no SEI com suas credenciais e, logo após fazer o login, saia do sistema. Assim, seu órgão ficará como padrão na tela de login
- Retirar das variáveis de entrada "2.3. Nome do Órgão** (ação nº 2)" - o código está sem essa variável

**Comment by IsaRomancini** [comment]
**Fluxo Extrair dados dos processos que estão em um bloco interno e passar essa lista para um excel:**
- Na seção "Importante", acrescentar: "Verifique se o nome do seu órgão já consta no campo "órgão" na tela de login do SEI. Caso não conste, entre no SEI com suas credenciais e, logo após fazer o login, saia do sistema. Assim, seu órgão ficará como padrão na tela de login

**Comment by Andrelamor** [comment]
> **Fluxo "trocar unidade do SEI"**
> 
> * Não sei se precisa, mas acho legal ter aquela seção de "Funções desenvolvidas pelo robô" com as atividades. O fluxo desenhado acho que não precisa.
> * Na seção "Importante", acrescentar: "Verifique se o nome do seu órgão já consta no campo "órgão" na tela de login do SEI. Caso não conste, entre no SEI com suas credenciais e, logo após fazer o login, saia do sistema. Assim, seu órgão ficará como padrão na tela de login
> * Retirar das variáveis de entrada "2.3. Nome do Órgão** (ação nº 2)" - o código está sem essa variável

então, @IsaRomancini, printei as ações em vez de colocar texto para "Funções", pois trata-se de uma função, somente, certo? como são poucas ações, não ficou carregado na página; enfim, um teste visual também para todxs terem suas percepções e avaliações;

sobre órgão, é a conversa de hoje sobre como construir os MVPs de forma mais genérica possível, sem ficarmos presos/submersos num mar de complexidade/sofisticação exagerados

**Comment by gabrielbdornas** [comment]
> * fazer login: https://automatiza-mg.github.io/automatizacoes/robos/login_sei/ @gabrielbdornas
> * [ ]  trocar unidade do SEI: https://automatiza-mg.github.io/automatizacoes/robos/sei_troca_unidade/
>   
>   * mudar código para colocar Órgão como Variável de entrada @Andrelamor (partir do ícone da lista de processos por causa do tab)

@Andrelamor e @YanVieira1905, fazendo a tela do robô que fará [login no SEI](https://automatiza-mg.github.io/automatizacoes/robos/login_sei/) e fiquei pensando se não seria melhor unir este robô com o de trocar a unidade. Seria melhor, sempre ao logar se certificar que a unidade está correta. Para os casos em que a troca de unidade possa fazer sentido dentro de algum fluxo poderíamos deixar também este robô. Neste sentido, teríamos no login sei um subfluxo para executar o login um para trocar unidade e outro para executar os dois (main).

**Comment by gabrielbdornas** [comment]
## Conferências finais MVPs:

- Power Automate:
  - [ ] Instâncias SEI denominadas `sei`.
  - [ ] Variáveis `snake_small_case`.

- Páginas Site:
  - [ ] Desenvolvedor (tabela inicial): Automatiza-mg.
  - [ ] E-mail (tabela inicial): simplificacao@planejamento.mg.gov.br.
  - [ ] Versão Automate.
