### ISSUE TITLE
Melhorar desempenho do site

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#76]
Desempenho do site publicado está ruim. Um exemplo é o mecanismo de pesquisa (search bar) que não está respondendo e a inicialização do servidor local que está demorando um tempo excessivo.

[Screencast from 30-01-2024 09:11:49.webm](https://github.com/automatiza-mg/automatizacoes/assets/49699290/9695ba38-6010-4b82-a7f7-a097b3f48b47)

[Este Issue](https://github.com/squidfunk/mkdocs-material/issues/1887) do repositório material-mkdocs relata algumas tentativas de otimizações, bem como alguns motivos geradores de lentidão. Neste mesmo Issue, encontrei a extensão Chrome [Google Lighthouse](https://chromewebstore.google.com/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk) para fazer uma análise de desempenho de uma página, bem como sugestões de melhoria.

[O report gerado no Google Lighthouse](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fautomatiza-mg.github.io%2Fautomatizacoes%2Fblog%2Fintrodu%25C3%25A7%25C3%25A3o-power-automate%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext) em 30/01/2024 mostra um desempenho muito baixo[^1]:

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/be7c9b9e-79ba-478e-bf21-400e0abfb518)

Penso que, além das medidas necessárias para melhoria do desempenho atual, devemos criar um processo que a cada novo conteúdo incluído o desempenho seja analisado para evitar perdas ao longo do tempo.

## Prováveis ações para melhoria de desempenho

- [ ] Analisar desempenho com imagens em formatos corretos.
- [ ] Criar canal YouTube para armazenar vídeos.
- [ ] Remover conteúdo não utilizado.

[^1]: Desempenho medido em 29/01/2024 havia sido de 59%

**Comment by gabrielbdornas** [comment]
@YanVieira1905 e @Andrelamor, revisão foi feita a partir do commit [6fd7f07b2827a9cee239a1f5c00f23f6d16a6344](https://github.com/automatiza-mg/automatizacoes/tree/6fd7f07b2827a9cee239a1f5c00f23f6d16a6344). Caso haja necessidade de buscar algum arquivo basta voltar nesta fase do projeto com `git checkout 6fd7f07b2827a9cee239a1f5c00f23f6d16a6344`.

**Comment by gabrielbdornas** [comment]
Pequena melhora no desempenho após mudança do padrão visual e limpeza de arquivos não utilizados em 07/02/2024.

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/a02fdc52-4424-45f9-a663-1d28b16a28e6)

**Comment by gabrielbdornas** [comment]
@YanVieira1905 e @Andrelamor, um teste que fiz hoje, 23/02/2024 e pareceu dar grande resultado no desempenho do site foi excluir o código-fonte dos robôs. Por se tratar de um site estático, acho que estes arquivos com o código-fonte acaba pesando muito o desempenho e principalmente o mecanismo de busca do sistema (que não está funcionando em produção). Uma solução para resolver o problema seria criarmos um repositório GitHub apenas para armazenar estes códigos fontes e no nosso site colocamos apenas o link para o raw deste código. Não teríamos o mesmo efeito visual, mas ganharíamos em eficiência. Acredito que vale o teste.

[Exemplo de link para raw do código](https://raw.githubusercontent.com/automatiza-mg/automatizacoes/main/docs/robos/aposentadoria/assets/codigo_fonte.txt).

**Comment by gabrielbdornas** [comment]
Mudanças Branch `76/melhorar-desempenho-site`:

- [ ] Melhorar modelo página robôs (login SEI).
- [ ] Levar códigos robôs repositório GitHub [biblioteca-de-robos](https://github.com/automatiza-mg/biblioteca-de-robos).
- [ ] Deletar arquivo `partials/modelo_robo/importante` após conferência de sua necessidade.
- [ ] Deletar arquivo `partials/modelo_robo/alem_disso` após conferência de sua necessidade.
- [ ] Aplicar modelo página robô (criada no robô login SEI) para todos os robôs.
- [ ] Testar todos os robôs disponíveis na biblioteca.

**Comment by Andrelamor** [comment]
> Pequena melhora no desempenho após mudança do padrão visual e limpeza de arquivos não utilizados em 07/02/2024.
> 
> ![image](https://private-user-images.githubusercontent.com/49699290/303125520-a02fdc52-4424-45f9-a663-1d28b16a28e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzc4NzEsIm5iZiI6MTcxMDE3NzU3MSwicGF0aCI6Ii80OTY5OTI5MC8zMDMxMjU1MjAtYTAyZmRjNTItNDQyNC00NWY5LWE2NjMtMWQyOGIxNmEyOGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE3MTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMzM0OGIxNWMzOWY2OTE2ZDE5YTRjZTgzNWVlOTkxMmM2ZWIwMDllYzBiN2FhZTEzOTZlOTljMDA3MDI2ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BjcfMnnnZ0X01xLOKDAZRO92HoKUhogwufxVgtO6F_k)

@gabrielbdornas temos condição de ver como o desempenho do site ficou após as alterações?

**Comment by gabrielbdornas** [comment]
Depois do #87 desempenho do site continua ruim:

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/5951319a-ca31-4e9e-ba68-6f5075b5e10d)

**Comment by Andrelamor** [comment]
@gabrielbdornas intrigante a medida de _'performance'_ medida pelo _Lighthouse_ da Google ter caído de 48 para 33%, mesmo após todas as tuas alterações e a aparente melhora relatada [aqui](https://github.com/automatiza-mg/automatizacoes/issues/76#issuecomment-1961843191)

O _total blocking time_ subiu de 550 para 2220 (4x mais espera de resposta da página?), o que me leva a questionar quais são os **componentes desse indicador de _performance_ e o quê seria possível tentar modificar no site, com o padrão MkDocs, além do que vc já fez. Ou se existe uma limitação intrínseca da versão não-paga, que estamos utilizando.

## componentes do indicador de _performance_ 

- 

## comparações com páginas diferentes

o primeiro screenshot [daqui](https://github.com/automatiza-mg/automatizacoes/issues/76#issue-2107749554) aponta para a página inicial do BLOG, não da _landing page_, vc reparou? Então os 35% iniciais são do blog. Eu repliquei o link da minha máquina e deu 48%.

## os outros 3 indicadores do Google _Lighthouse_

Acessibility, Best Practices e SEO: estão um pouco melhor no blog que a landing page. Seria consequência do formato da página do blog em si? (i.e. metadados de classificação dos posts, paginação, só textos e quase zero imagens...)

**Comment by Andrelamor** [comment]
## as sugestões do _Google Lighthouse_ para o [post do BLOG](https://automatiza-mg.github.io/automatizacoes/blog/introdu%C3%A7%C3%A3o-power-automate/):
- gráfico do que está pesando mais: https://googlechrome.github.io/lighthouse/treemap/?gzip=1#
- como minimizar impacto de códigos de terceiros (potencial de redução de 800ms): https://web.dev/articles/optimizing-content-efficiency-loading-third-party-javascript?utm_source=lighthouse&utm_medium=lr&hl=pt-br
- como eliminar _render-blocking-resources_ (potencial de redução de 4.300ms)
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/2499b10e-7f59-44a2-9d7d-cf66f3183fe7)

**Comment by Andrelamor** [comment]
uma nota de rodapé segura a execução mais 'fluida' da página por 3,8 segundos? 
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/b78d7e87-be32-4267-b193-c4d644d8e03c)

**Comment by Andrelamor** [comment]
@gabrielbdornas baseado nas indicações do meu penúltimo comentário, pacotes/bibliotecas/componentes **vega, tablesort e mathjax** respondem por 5 dos 13 scripts de "terceiros" que prejudicam a renderização das páginas. Essas coisas eram pra nos auxiliar a visualizar tabelas e gráficos, mas não estão sendo utilizadas.

Então tentei localizar esses arquivos `.js` residuais (uma vez que vc já tinha feito essa triagem), mas não consegui excluí-los (aparecem esmaecidos seus nomes de arquivos no Sublime). Dois deles estão na pasta site/assets, mas fazem a renderização das fórmulas matemáticas do post do Lucas:

![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/2defc9f0-eec5-412f-865c-98bd745350cb)


Reduzir impacto de códigos de terceiros teria o maior potencial de 'economia' de tempo, segundo indicou o _Google Lighthouse_. Paralelamente, a ferramenta _ Catch point Webpage Performance_ nos apresenta um relatório *excessivamente extenso*, cheio de apontamentos e possibilidades de melhoria (sendo que usei o mesmo link de um posto do blog).

**Comment by gabrielbdornas** [comment]
> o primeiro screenshot [daqui](https://github.com/automatiza-mg/automatizacoes/issues/76#issue-2107749554) aponta para a um [único post do blog](https://github.com/automatiza-mg/automatizacoes/issues/76#issue-2107749554), não da _landing page_, vc reparou? Então os 35% iniciais se referem a esse post no blog. Eu [repliquei o link do _lighthouse report viewer_ na minha máquina](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fautomatiza-mg.github.io%2Fautomatizacoes%2Fblog%2Fintrodu%25C3%25A7%25C3%25A3o-power-automate%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext) e deu 46%.

@Andrelamor, talvez tenha ficado mal escrito, neste relato queria demonstrar o quando a ferramenta de busca estava lenta, sem perceber fiz a simulação [neste post do blog](https://automatiza-mg.github.io/automatizacoes/blog/introdu%C3%A7%C3%A3o-power-automate/). Não percebi que não estava na página inicial. Se rodar o Lighthouse neste post, hoje, verá que seu desempenho é maior. Isso causou uma confusão. O ponto que dever ser focado, na minha opinião, são os 33% de desempenho da página inicial. 

> * já para a _landing page_, versão MOBILE, o _total blocking time_ subiu de 550 para 2220 (4x mais espera de resposta da página?), o que me leva a questionar quais são os **componentes desse indicador de _performance_** e o quê seria possível tentar modificar no site, com o padrão MkDocs, além do que vc já fez. Ou se existe uma limitação intrínseca da versão não-paga, que estamos utilizando.

Não acho que isso é uma questão relativa à versão paga ou gratuita do material e sim como configurei a renderização de bibliotecas externas, imagens e vídeos (os próprios apontamentos nos falam isso, como você bem observou em comentários subsequentes). A título de comparação, rodei o Lighthouse na [página inicial da documentação mkdocs-material](https://squidfunk.github.io/mkdocs-material/) e o desempenho foi de 68%. O pode nos mostrar que 100% pode ser uma meta "inatingível". Obs.: Na minha opinião a navegação neste exemplo é impecável.

Sendo assim, minhas ações para o momento serão reduzir o tamanho das imagens ([utilizando o formato webp](https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images/?utm_source=lighthouse&utm_medium=lr)) e utilizar um serviço externo para hospedá-las. Ao fazer isso com o banner [neste commit](https://github.com/automatiza-mg/automatizacoes/commit/2b7b7c582788fd089406dddcb93bcd9743a9c5d7) tivemos um ganho de 1%:

- Verificação antes do [commit em questão]((https://github.com/automatiza-mg/automatizacoes/commit/2b7b7c582788fd089406dddcb93bcd9743a9c5d7)):

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/2d815c92-623f-4f7e-bdfe-fd54cc41db9f)

- Verificação depois do [commit em questão]((https://github.com/automatiza-mg/automatizacoes/commit/2b7b7c582788fd089406dddcb93bcd9743a9c5d7)).

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/93a4ebdd-1a46-43f1-be7f-cbe37817bc36)

Deixarei a análise das bibliotecas externas para segundo momento pois ainda não entendi como posso resolver.

**Comment by gabrielbdornas** [comment]
@Andrelamor:

> Vou excluir o que achei pertinente em
> 
> https://github.com/automatiza-mg/automatizacoes/blob/841be5cee101547d1374ae169fbcb2eae8ed7b4a/mkdocs.yml#L95
> 
> na branch 76.

Favor observar [este comentário](https://github.com/automatiza-mg/automatizacoes/commit/adaea30c09320805676301674b05220766a9b9c3#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2L98)

**Comment by gabrielbdornas** [comment]
Melhora significante de desempenho após [este commit](https://github.com/automatiza-mg/automatizacoes/commit/6e97041a249daa6db545351a23ed3034d73ac4f9):

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/0fb6efa8-f1ab-4904-9496-aac64a7539af)

Vou tentar retirar todos os robôs com código `.txt` para verificar se ferramenta de busca funcionará apenas no clique, mas ela já está funcionando (apesar de demorar um pouco).

**Comment by gabrielbdornas** [comment]
Depois [deste commit](https://github.com/automatiza-mg/automatizacoes/commit/9fc3a2e63ec131c51fac8fadf7652bbd5b1065d9), registrada [neste comentário](https://github.com/automatiza-mg/automatizacoes/issues/76#issuecomment-1996073831) ferramenta de busca passou a funcionar como esperado.

**Comment by gabrielbdornas** [comment]
@dcd-github-admin, após [esta constatação](https://github.com/automatiza-mg/automatizacoes/issues/76#issuecomment-1996079794), acredito que podemos fechar esta Issue. Uma boa prática, de agora em diante, será testar o desempenho do site a cada novo commit, evitando assim um acúmulo de erros ao longo do tempo que deixe o site lento.

**Comment by Andrelamor** [comment]
> Depois [deste commit](https://github.com/automatiza-mg/automatizacoes/commit/9fc3a2e63ec131c51fac8fadf7652bbd5b1065d9), registrada [neste comentário](https://github.com/automatiza-mg/automatizacoes/issues/76#issuecomment-1996073831) ferramenta de busca passou a funcionar como esperado.
> 
> Desempenho também melhoraram bastante:
> 
> ![image](https://private-user-images.githubusercontent.com/49699290/312649606-aeb256dd-f9cb-4ce1-b5b2-9a58ec42800f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTI1NTksIm5iZiI6MTcxMDUxMjI1OSwicGF0aCI6Ii80OTY5OTI5MC8zMTI2NDk2MDYtYWViMjU2ZGQtZjljYi00Y2UxLWI1YjItOWE1OGVjNDI4MDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE0MTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNDJiY2QwYjI0NzJkYmRmZjM1ZTg0NmJiMDM0NGEyYjJlMzJlOGRiYWUxZDNhZDgyMDMyZGNiYzM4NjQ1MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VgnmQVC18yMNPQ8IwxNKppwFna9qTnhGka_aoVFRNUU)
> 
> @dcd-github-admin, solicito que naveguem nas páginas para ver se aquela quebra relatada por @YanVieira1905 irá acontecer novamente.
> 
> A partir de amanhã voltarei com os robôs sem os códigos fonte.

vide https://github.com/automatiza-mg/automatizacoes/commit/adaea30c09320805676301674b05220766a9b9c3#commitcomment-139833956

**Comment by Andrelamor** [comment]
> @dcd-github-admin, após [esta constatação](https://github.com/automatiza-mg/automatizacoes/issues/76#issuecomment-1996079794), acredito que podemos fechar esta Issue. Uma boa prática, de agora em diante, será testar o desempenho do site a cada novo commit, evitando assim um acúmulo de erros ao longo do tempo que deixe o site lento.

@gabrielbdornas teste de agora sem usar o site, só baixei a extensão Lighthouse e apliquei:
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/5fa7bec3-5b4c-424a-8b5a-4592a2805392)

![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/7335e80b-a8f2-4eff-8e0d-f53c5ce75d42)

**Comment by Andrelamor** [comment]
Achei a outra ferramenta mais detalhada, embora menos intuitiva, também apontou melhoria como no lighthouse: https://automatiza-mg.github.io/automatizacoes/
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/28d2d515-3c3a-4bf7-9df1-913c6790c633)
