### ISSUE TITLE
Criar código Javascript para buscar título e número de documentos de um processo SEI

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#79]
Demanda não estava funcionando com os códigos JS que estamos utilizando até o momento.

**Comment by gabrielbdornas** [comment]
Após bastante pesquisa percebi que as funções `document.getElementsBy` só funcionavam após clicar com botão direito e inspecionar os elementos. Isso me levou a crer que a página não estava totalmente carregada.

[Esta resposta stackoverflow](https://stackoverflow.com/a/67567588/11755155) deu como sugestão achar o `iframe` antes de selecionar os elementos:

```
window.top    //first start from the main top window
   .document.querySelector('iframe')  //now select the iFrame
   .contentDocument.querySelector('[name=username]') //finally do our selector
```

Fazendo isso funcionou perfeitamente.

@YanVieira1905 o robô para teste ficou muito longo para salvar aqui. Pensei em colocar no site. O que acha?

**Comment by gabrielbdornas** [comment]
@automatiza-mg/dcd , esta é a beleza de documentar nossa ações utilizando o Github. A dúvida de @felpsop em nossa reunião de hoje (24/05/2024) está, exatamente, documentado aqui, problema é solução! Passei por esta pérola três meses atrás. Se não tivesse escrito, não teria lembrado. Se não tivesse escrito não conseguiria auxiliar vocês, transmitido este conhecimento.

Uma de nossas brincadeiras na CGE, ao abrir uma apresentação [era](
https://transparencia-mg.github.io/reveal.js/presentations/20230804_minas_de_dados_overview_dta/index.html#/2):

> VAMOS FAZER UM EXPERIMENTO MENTAL...
Se uma informação só existe com a pessoa que a gerou, e essa pessoa não está disponível, essa informação realmente existe? 

Segundo [Karen Cranston](https://x.com/kcranstn/status/370914072511791104):

> motivating git: You mostly collaborate with yourself, and me-from-two-months-ago never responds to email.

**Comment by gabrielbdornas** [comment]
@automatiza-mg/dcd , esta é a beleza de documentar nossa ações utilizando o Github. A dúvida de @felpsop em nossa reunião de hoje (24/05/2024) está, exatamente, documentado aqui, problema é solução! Passei por esta pérola três meses atrás. Se não tivesse escrito, não teria lembrado. Se não tivesse escrito não conseguiria auxiliar vocês, transmitido este conhecimento.

Uma de nossas brincadeiras na CGE, ao abrir uma apresentação [era](
https://transparencia-mg.github.io/reveal.js/presentations/20230804_minas_de_dados_overview_dta/index.html#/2):

> VAMOS FAZER UM EXPERIMENTO MENTAL...
Se uma informação só existe com a pessoa que a gerou, e essa pessoa não está disponível, essa informação realmente existe? 

Segundo [Karen Cranston](https://x.com/kcranstn/status/370914072511791104):

> motivating git: You mostly collaborate with yourself, and me-from-two-months-ago never responds to email.

**Comment by felpsop** [comment]
Excelente @gabrielbdornas muito obrigado!

**Comment by gabrielbdornas** [comment]
> Excelente @gabrielbdornas muito obrigado!

@felpsop , conseguiram finalizar o código que iniciamos na sexta? Se não, o que foi tentado e qual o erro encontrado?

**Comment by felpsop** [comment]
@gabrielbdornas não, mas ajustei o fluxo com a ação de clicar em link de página da web e deu certo, a execução não apresentou erros em uma amostragem de 200 processos.
