### ISSUE TITLE
Sugestão de nova ferramenta para construção do Formulário de solicitação de Imersão

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#83]
@YanVieira1905, hoje, trabalhando no [Issue 81](https://github.com/automatiza-mg/automatizacoes/issues/81) e atualizando o atual [Formulário de solicitação de imersão](https://forms.office.com/Pages/DesignPageV2.aspx?prevorigin=OfficeDotCom&origin=NeoPortalPage&lang=en-US&subpage=design&id=fK7T5Tib3kigh_ZzSih1dPWy2Jh3mIJCosCTPKvD6BVUMFFGMFo3Nk1PU1FVV0hDU0tSMUJRTFBORSQlQCN0PWcu) feito no Microsoft Forms percebi que ele, não sei por que motivo, apaga mudanças que fizemos após algum tempo. Acredito que foi exatamente isso que aconteceu na sexta, quando o texto da introdução do formulário foi apagado. Para não ficarmos brigando com a ferramenta e sujeitos a este tipo de inconstâncias sugiro a utilização da ferramenta https://tally.so/, descoberta por nosso colega @lucasfainblat. 

Hoje, 05/04/2024, no período da tarde, testei a ferramenta e achei fantástica. Fácil de utilizar, intuitiva e o que é melhor, não apresenta os erros de perda de dados relatados acima. Iniciei a construção de um formulário com os mesmos campos e configurações [aqui](https://tally.so/r/mYW6Jv). 

Outra vantagem será a possibilidade de "embedarmos" o formulário no nosso site (conforme vontade inicial), fazer isso com este formulário será muito fácil, conforme teste rápido feito em meu ambiente local (este é apenas um exemplo, podemos fazer várias configurações de embed, inclusive incluí-lo em toda página):

![Image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/d1114690-7c39-4077-9c09-b70b551600fb)

Operacionalmente falando é possível cadastrar o recebimento de um e-mail toda vez que um novo formulário for preenchido. Este e-mail poderia funcionar como um trigger no Automate web para diversas ações, tais como:

- Cálculo da prioridade.
- E-mail de agradecimento ao solicitante.
- Publicação/atualização em formato aberto.
- Entre outros.

Criei uma conta do tally.so utilizando o e-mail da simplificação, desta maneira, todos podem ter acesso para edição deste formulário, bem como criar outros.

**Comment by gabrielbdornas** [comment]
@dcd-github-admin, [Formulário](https://tally.so/r/mYW6Jv) validado com @YanVieira1905 em 07/03/2024. Peço que nos ajudem a testar novamente formato e textos.

**Comment by Andrelamor** [comment]
> @dcd-github-admin, [formulário](https://tally.so/r/mYW6Jv) validado com @YanVieira1905 em 07/03/2024. Peço que nos ajudem a testar novamente formato e textos. Vou deixar o Issue aberto até sexta, 15/03/2024, para vocês incluírem as sugestões de melhorias em comentários abaixo.

@gabrielbdornas:
1 - sensacional o exemplo de resposta pré-preenchido em cinza esmaecido nas perguntas abertas;
2 - a adição da explicação de dados estruturados também ficou joia, bem como a exigência de 50 caracteres para que o requerente descreva a tentativa de automação/explicação do fluxo
3 - ao apertar o botão 'enviar' ao final, o formulário voltou diretamente para a landing page do Automatiza, não dando a certeza ao respondente que o 'formulário foi enviado com sucesso'; na versão anterior do Microsoft Forms, tinha uma mensagem padrão ao final, certo?

**Comment by gabrielbdornas** [comment]
> 4 - Esse ainda não deve estar com o email configurado pra receber uma confirmaçaõ, né? não veio email

@Andrelamor, a única sugestão que ainda não atendi foi esta. Vou implementá-la em #81. Vou fechar este Issue, pois considero que conseguimos uma primeira versão do formulário.
