### ISSUE TITLE
Reunião DCD 2024-03-11

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#86]
## projetos - priorização
- CET: 
  - apresentação pela SCID dia 26
- FHEMIG: 
  - reunião Renata 4ª
  - autorização para acesso à API do CFM, liberado em um mês
- COHAB: 
  - reunião Danilo
- SEDE: 
  - teve uma reunião hoje 
  - ainda vão listar quais processos mais importantes para liberdade econômica - 5 a 10 processos
- SEAPA:
  - reaplicação do robô de faturas da CEMIG (apenas 2 faturas)
  - atualização patrimônio SIAD (robô replicável para o site), tempo previsto de uma tarde
- SEDESE:
   - Fundo Estadual de Assistência Social
   - verificar acesso ao relatório do BO   
- SEJUSP:
  - liberação de servidores para trabalharem em processos de automatização 
- FJP:
  - taxação rodar na próxima quinta, a partir da planilha pronta
  - fluxo completo em MAIO (abril: comunicação com os professores)
  - robô para avisar professor que não lançou frequência
  - análise na base de dados para professores que trabalharam mais de 40h/mês (retenção excedente)
  - o que ê mês corrente e o mês anterior para ser identificado na planilha da SOLIS   

-  SCAP: ver https://github.com/automatiza-mg/imersao-scap/issues/13 
- API SEI
  - possibilidade integrar com sistema SEJUSP para posse DEPEN 

## site
- avaliação para migração de domínio
- velocidade do site: ver
  - códigos com 500 páginas no word podem estar pesando
- Analytics a ser ligado após migração de domínio
- sistema de comentários: #84
- escopo de robôs replicáveis (ex.: re-descrição e compartimentação do robô do PAE - replicável de descompactar arquivos)

**Comment by gabrielbdornas** [comment]
@dcd-github-admin, não falamos nada sobre #68 nesta reunião? Se não, acredito que deveríamos falar na próxima.
