### ISSUE TITLE
reunião projeto transformação digital perícia 2024-03-15

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#90]
- 25 processos
- sistema em desenvolvimento, s ser entregue em junho, com telas já desenhadas no Figma
- MVP = grande entrega e não MVP de fato
- etapas de qq serviço: solicitação (servidor/setores) > análise (médico perito) > conclusão
- gargalo: perícia com data estendida (acúmulo de atestados para uma mesma marcação)
  - sistema exige novo formulário para cada solicitação, em caso de nova intercorrência, marcando para a mesma data inicial
  - envio automático de email e SMS (questionamento da necessidade de SMS em eventual renovação de contrato com empresa responsável por esse serviço) 
- arquivos físicos no Maleta (e em todas as regionais) para análise do médico perito, com previsão de digitalização de todos os prontuários/documentos  
- resistência dos peritos à digitalização
- demostração do ambiente de homologação das telas de solicitação via portal do servidor
- SIPEMSO/perfil dos médicos em desenvolvimento fora do ar

- LTS Perícia Documental (passivo de 150mil)
  - muita demanda para o atual número de médicos
  - gargalos administativos
- possibilidade de automação da checagem das infos de preenchimento obrigatório no atestado 
  - adicionar prints no SISAP à tela do SEI (seão tratadas no sistema em construção) 
- BIM não existe mais, somente o atestado  
- reunião de alinhamento com Alvimar para definir frentes de atuação do LAB

**Comment by Andrelamor** [comment]
- [ ] investigar bases legais dos fluxos

**Comment by gabrielbdornas** [comment]
> * [ ]  investigar bases legais dos fluxos, para entender limites da atuação dos médicos:
>   
>   * https://www.portaldoservidor.mg.gov.br/licenca-tratamento-saude-efetivo
>   * https://www.almg.gov.br/legislacao-mineira/LCP/121/2011/
>   * https://www.almg.gov.br/legislacao-mineira/DEC/48249/2021/
>   * https://www.pesquisalegislativa.mg.gov.br/LegislacaoCompleta.aspx?cod=204368&marc=

@Andrelamor, como esse Issue se trata de uma ata de reunião, eu o fechei e completei as informações referentes ao projeto "Planner". Estes itens de investigação sugiro criar um novo Issue no repositório Handbook. Se o projeto vingar, realmente, abrimos um repositório para ele.

Outr sugestão, tendo em vista que esta ainda é uma discussão, seria levar o próprio Issue da reunião para o repositório do Handboo.
