### ISSUE TITLE
Botão para baixar documentos Excel (arquivados como `.csv`) não funcionando em produção - Perguntar Stackoverflow.

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#91]
Teste feito no robô de [consulta de situação cadastral cagef](https://automatiza-mg.github.io/automatizacoes/robos/consulta_situacao_cadastral_cagef/#montando-o-seu-robo) mostra o erro. Interessante que o download ocorre normalmente em ambiente local.

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/b89082a9-cdfc-4eb6-aca6-b8071d76f4d8)

**Comment by gabrielbdornas** [comment]
[Este comentário](https://stackoverflow.com/questions/71521948/javascript-functions-not-working-on-github-pages-but-working-locally#:~:text=%40Bravo%20Thank%20you%20for%20your%20help%20(first%20reply..!).%20I%27ve%20just%20resolved%20my%20problem%20by%20just...%20deleting%20all%20annotations%20(//).%20Still%20wondering%20why%20it%20did%20work%20on%20local%20host%2C%20but%20anyway%20I%20solved%20it%20now.) sugere apenas retirar comentários do arquivo.

**Comment by gabrielbdornas** [comment]
Download realizado com sucesso após [este commit](https://github.com/automatiza-mg/automatizacoes/commit/d19888c8b57282a76d8b4d9da39af967e41321e6). Uma observação, que não chega ser um grande problema, é a necessidade de atualizar a página para que o download funcione para um segundo click.

**Comment by gabrielbdornas** [comment]
> Download realizado com sucesso após [este commit](https://github.com/automatiza-mg/automatizacoes/commit/d19888c8b57282a76d8b4d9da39af967e41321e6). Uma observação, que não chega ser um grande problema, é a necessidade de atualizar a página para que o download funcione para um segundo click.

Resolvi o problema do click único com ajuda do [Gemini](https://gemini.google.com/share/f0f696b4962a).

**Comment by gabrielbdornas** [comment]
Vou ter que reabrir o Issue porque o problema não foi resolvido. @YanVieira1905 não conseguiu abrir o arquivo durante apresentação AESTs. Um workaround para este momento é atualizar a página. Quando a página abre, não sei porque motivo, ele não está encontrando o elemento.

**Comment by gabrielbdornas** [comment]
Após tentar quase duas tardes resolvi incluir o próprio Excel no repositório, [neste commit](https://github.com/automatiza-mg/automatizacoes/commit/37e8a0d5aad3d3032c610c5a34f7b8a3a5a4410a). Vou deixar este Issue em backlog e, pensar, se vale a pena abrir uma pergunta no Stackoverflow.

**Comment by gabrielbdornas** [comment]
Pelo visto o problema de carregamento do Javascript não está ocorrendo somente nesta situação. Notei que ele também ocorre nos fluxos mermaid. Encontrei [este issue](https://github.com/squidfunk/mkdocs-material/issues/6661) no repositório mkdocs-material que pode explicar o problema como relacionado a instalação do MathJax. O problema é que não temos mais o MathJax instalado, apenaso KateX.

**Comment by gabrielbdornas** [comment]
Posso ter encontrado a solução com auxílio [deste Issue](https://github.com/squidfunk/mkdocs-material/issues/5901#issue-1868286126), que fala sobre problemas após a configuração da feature `enables navigation.instant`. Lembrei que fiz esta [configuração](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#instant-loading) com o objetivo de melhorar o desempenho do site (#76), mas ao retirar esta configuração tudo voltou ao normal

https://github.com/automatiza-mg/automatizacoes/blob/9ebb02478677ae8fa87caf60c474b6fd28db73b8/mkdocs.yml#L37-L38. Abrirei um PR para testar.

**Comment by gabrielbdornas** [comment]
@YanVieira1905, @Andrelamor comentou comigo que você teve dificuldade para baixar a planilha modelo durante a apresentação para as AESTs. Estou tentando resolver isso desde a última sexta. Pensei que tinha conseguido, mas graças a sua falha durante a apresentação vi que não. Encontrei, inclusive, outros, como relatado [aqui](https://github.com/automatiza-mg/automatizacoes/issues/91#issuecomment-2007748942). Acredito que agora sim. Peço que teste novamente, por favor.

Fix after #95 (Nome PR deveria iniciar com 91 e não 71 - Falha minha)

**Comment by Andrelamor** [comment]
> @YanVieira1905, @Andrelamor comentou comigo que você teve dificuldade para baixar a planilha modelo durante a apresentação para as AESTs. Estou tentando resolver isso desde a última sexta. Pensei que tinha conseguido, mas graças a sua falha durante a apresentação vi que não. Encontrei, inclusive, outros, como relatado [aqui](https://github.com/automatiza-mg/automatizacoes/issues/91#issuecomment-2007748942). Acredito que agora sim. Peço que teste novamente, por favor.
> 
> Fix after #95 (Nome PR deveria iniciar com 91 e não 71 - Falha minha)

@gabrielbdornas cliquei no hiperlink a planilha foi baixada
