### ISSUE TITLE
Limpar branchs antigas

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/automatizacoes#96]
@Andrelamor, estou fazendo um esforço para deixar o repositório o mais limpo possível. Isso inclui [branchs](https://github.com/automatiza-mg/automatizacoes/branches) antigas e que não fazem mais sentido.

Gostaria de saber se você se opõe a deleção de todas as branchs e deixar somente a main. Você está, atualmente, trabalhando em alguma das ativas?

Também fiz uma configuração para deletar toda branch após o merge de um PR:

![image](https://github.com/automatiza-mg/automatizacoes/assets/49699290/3a34113d-2b7e-41c0-a44f-1a188cc5f783)

Afinal, branch mergiada significa que seu commit foi parar na main. Mesmo assim, como a própria figura acima diz, é possível restaurar as mesmas, caso seja necessário.

**Comment by Andrelamor** [comment]
> [@Andrelamor](https://github.com/Andrelamor), estou fazendo um esforço para deixar o repositório o mais limpo possível. Isso inclui [branchs](https://github.com/automatiza-mg/automatizacoes/branches) antigas e que não fazem mais sentido.
> 
> Gostaria de saber se você se opõe a deleção de todas as branchs e deixar somente a main. Você está, atualmente, trabalhando em alguma das ativas?
> 
> Também fiz uma configuração para deletar toda branch após o merge de um PR:
> 
> ![image](https://private-user-images.githubusercontent.com/49699290/314187860-3a34113d-2b7e-41c0-a44f-1a188cc5f783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODAxMjQsIm5iZiI6MTcxMDg3OTgyNCwicGF0aCI6Ii80OTY5OTI5MC8zMTQxODc4NjAtM2EzNDExM2QtMmI3ZS00MWMwLWE0NGYtMWExODhjYzVmNzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIwMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MjM3MTVhZmYzMWE2N2VlYjQ2NzIyMDc2NDhmOTJkZTljM2M2YjJlNWZkZjdlYjY0MDZkZjlmYTUyYWZiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.86qMuGIMP2fjcHU0g93NpaIM-heObEHMzzKSE9to_Nw)
> 
> Afinal, branch mergiada significa que seu commit foi parar na main. Mesmo assim, como a própria figura acima diz, é possível restaurar as mesmas, caso seja necessário.

@gabrielbdornas não estou com outra branch em atividade, creio que pode apagar, sim
